/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetTemplateSectionsRequest {
    /**
     * Filter template sections by organization.
     */
    org?: string | string[];
    /**
     * Filter template sections by language.
     */
    lang?: string | string[];
}
