/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetTemplatesRequest {
    /**
     * Filter templates by organization.
     */
    org?: string | null;
    /**
     * Filter templates by language.
     */
    lang?: string | null;
    /**
     * Filter templates by their status.
     */
    templateStatus?: string | null;
}
