/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Can be "base", "enhanced", "premier". By default, only the highest tier is accessible. Check https://docs.corti.ai/about/languages for more.
 */
export type RequestTranscriptCreateModelName = "premier" | "enhanced" | "basic";
export const RequestTranscriptCreateModelName = {
    Premier: "premier",
    Enhanced: "enhanced",
    Basic: "basic",
} as const;
