// This file was auto-generated by Fern from our API Definition.

/** Controls how recognized transcript text is processed before it is returned. `standard` (default) applies Corti's standard transcript processing and configured transcript features. `raw` returns the core speech recognition result without transcript transformations or enhancements, which can reduce latency and processing cost but may reduce transcript accuracy. When `raw` is defined, features that transform transcript text (such as formatting or replacements) are not available; features that describe the recognition result (such as timestamps, word-level output, diarization, and audio events) remain supported where applicable. The `text` and `rawTranscriptText` fields contain the same core recognition result. */
export const TranscriptsCreateRequestTranscriptProcessing = {
    Standard: "standard",
    Raw: "raw",
} as const;
export type TranscriptsCreateRequestTranscriptProcessing =
    (typeof TranscriptsCreateRequestTranscriptProcessing)[keyof typeof TranscriptsCreateRequestTranscriptProcessing];
