/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes transcript attribute for sorting
 */
export type TranscriptsListRequestSort = "createdAt" | "updatedAt";
export const TranscriptsListRequestSort = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
