/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Corti from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace Documents {
    export interface Options {
        environment: core.Supplier<environments.CortiEnvironment | environments.CortiEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the Tenant-Name header */
        tenantName: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Tenant-Name header */
        tenantName?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Documents {
    protected readonly _options: Documents.Options;

    constructor(_options: Documents.Options) {
        this._options = _options;
    }

    /**
     *  List Documents
     *
     * @param {Corti.Uuid} id - The interaction ID representing the context for the request. Must be a valid UUID.
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Corti.BadRequestError}
     * @throws {@link Corti.ForbiddenError}
     * @throws {@link Corti.InternalServerError}
     * @throws {@link Corti.GatewayTimeoutError}
     *
     * @example
     *     await client.documents.list("f47ac10b-58cc-4372-a567-0e02b2c3d479")
     */
    public list(
        id: Corti.Uuid,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<Corti.ResponseDocumentList> {
        return core.HttpResponsePromise.fromPromise(this.__list(id, requestOptions));
    }

    private async __list(
        id: Corti.Uuid,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<Corti.ResponseDocumentList>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).base,
                `interactions/${encodeURIComponent(id)}/documents/`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "Tenant-Name": requestOptions?.tenantName,
                }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Corti.ResponseDocumentList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Corti.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Corti.ForbiddenError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Corti.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Corti.GatewayTimeoutError(
                        _response.error.body as Corti.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CortiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CortiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CortiTimeoutError("Timeout exceeded when calling GET /interactions/{id}/documents/.");
            case "unknown":
                throw new errors.CortiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     *  Generate Document.
     *
     * @param {Corti.Uuid} id - The interaction ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.RequestDocumentCreate} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Corti.BadRequestError}
     * @throws {@link Corti.ForbiddenError}
     * @throws {@link Corti.InternalServerError}
     * @throws {@link Corti.GatewayTimeoutError}
     *
     * @example
     *     await client.documents.create("f47ac10b-58cc-4372-a567-0e02b2c3d479", {
     *         context: [{
     *                 type: "facts",
     *                 data: [{
     *                         text: "text",
     *                         source: "core"
     *                     }]
     *             }],
     *         templateKey: "templateKey",
     *         outputLanguage: "outputLanguage"
     *     })
     */
    public create(
        id: Corti.Uuid,
        request: Corti.RequestDocumentCreate,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<Corti.ResponseDocumentRead> {
        return core.HttpResponsePromise.fromPromise(this.__create(id, request, requestOptions));
    }

    private async __create(
        id: Corti.Uuid,
        request: Corti.RequestDocumentCreate,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<Corti.ResponseDocumentRead>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).base,
                `interactions/${encodeURIComponent(id)}/documents/`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "Tenant-Name": requestOptions?.tenantName,
                }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Corti.ResponseDocumentRead, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Corti.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Corti.ForbiddenError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Corti.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Corti.GatewayTimeoutError(
                        _response.error.body as Corti.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CortiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CortiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CortiTimeoutError("Timeout exceeded when calling POST /interactions/{id}/documents/.");
            case "unknown":
                throw new errors.CortiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     *  Get Document.
     *
     * @param {Corti.Uuid} id - The interaction ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.Uuid} documentId - The document ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.DocumentsGetRequest} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Corti.BadRequestError}
     * @throws {@link Corti.ForbiddenError}
     * @throws {@link Corti.InternalServerError}
     * @throws {@link Corti.GatewayTimeoutError}
     *
     * @example
     *     await client.documents.get("f47ac10b-58cc-4372-a567-0e02b2c3d479", "f47ac10b-58cc-4372-a567-0e02b2c3d479")
     */
    public get(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        request: Corti.DocumentsGetRequest = {},
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<Corti.ResponseDocumentRead> {
        return core.HttpResponsePromise.fromPromise(this.__get(id, documentId, request, requestOptions));
    }

    private async __get(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        request: Corti.DocumentsGetRequest = {},
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<Corti.ResponseDocumentRead>> {
        const { context } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (context != null) {
            _queryParams["context"] = context.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).base,
                `interactions/${encodeURIComponent(id)}/documents/${encodeURIComponent(documentId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "Tenant-Name": requestOptions?.tenantName,
                }),
                requestOptions?.headers,
            ),
            queryParameters: _queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Corti.ResponseDocumentRead, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Corti.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Corti.ForbiddenError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Corti.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Corti.GatewayTimeoutError(
                        _response.error.body as Corti.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CortiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CortiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CortiTimeoutError(
                    "Timeout exceeded when calling GET /interactions/{id}/documents/{documentId}.",
                );
            case "unknown":
                throw new errors.CortiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Corti.Uuid} id - The interaction ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.Uuid} documentId - The document ID representing the context for the request. Must be a valid UUID.
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Corti.ForbiddenError}
     * @throws {@link Corti.NotFoundError}
     * @throws {@link Corti.InternalServerError}
     * @throws {@link Corti.GatewayTimeoutError}
     *
     * @example
     *     await client.documents.delete("f47ac10b-58cc-4372-a567-0e02b2c3d479", "f47ac10b-58cc-4372-a567-0e02b2c3d479")
     */
    public delete(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(id, documentId, requestOptions));
    }

    private async __delete(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).base,
                `interactions/${encodeURIComponent(id)}/documents/${encodeURIComponent(documentId)}`,
            ),
            method: "DELETE",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "Tenant-Name": requestOptions?.tenantName,
                }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Corti.ForbiddenError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Corti.NotFoundError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Corti.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Corti.GatewayTimeoutError(
                        _response.error.body as Corti.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CortiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CortiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CortiTimeoutError(
                    "Timeout exceeded when calling DELETE /interactions/{id}/documents/{documentId}.",
                );
            case "unknown":
                throw new errors.CortiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Corti.Uuid} id - The interaction ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.Uuid} documentId - The document ID representing the context for the request. Must be a valid UUID.
     * @param {Corti.RequestDocumentUpdate} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Corti.BadRequestError}
     * @throws {@link Corti.ForbiddenError}
     * @throws {@link Corti.InternalServerError}
     * @throws {@link Corti.GatewayTimeoutError}
     *
     * @example
     *     await client.documents.update("f47ac10b-58cc-4372-a567-0e02b2c3d479", "f47ac10b-58cc-4372-a567-0e02b2c3d479")
     */
    public update(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        request: Corti.RequestDocumentUpdate = {},
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<Corti.ResponseDocumentRead> {
        return core.HttpResponsePromise.fromPromise(this.__update(id, documentId, request, requestOptions));
    }

    private async __update(
        id: Corti.Uuid,
        documentId: Corti.Uuid,
        request: Corti.RequestDocumentUpdate = {},
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<Corti.ResponseDocumentRead>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)).base,
                `interactions/${encodeURIComponent(id)}/documents/${encodeURIComponent(documentId)}`,
            ),
            method: "PATCH",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({
                    Authorization: await this._getAuthorizationHeader(),
                    "Tenant-Name": requestOptions?.tenantName,
                }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Corti.ResponseDocumentRead, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Corti.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Corti.ForbiddenError(_response.error.body as Corti.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Corti.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Corti.GatewayTimeoutError(
                        _response.error.body as Corti.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CortiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CortiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CortiTimeoutError(
                    "Timeout exceeded when calling PATCH /interactions/{id}/documents/{documentId}.",
                );
            case "unknown":
                throw new errors.CortiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
