/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         encounter: {
 *             identifier: "identifier",
 *             status: "planned",
 *             type: "first_consultation"
 *         }
 *     }
 */
export interface InteractionsCreateRequest {
    /** A unique identifier for the medical professional responsible for this interaction. If nulled, automatically set to a uuid. */
    assignedUserId?: Corti.Uuid;
    /** Details about the encounter. */
    encounter: Corti.InteractionsEncounterCreateRequest;
    /** Optional patient details. */
    patient?: Corti.InteractionsPatient;
}
