/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         encounter: {
 *             identifier: "identifier",
 *             status: "planned",
 *             type: "first_consultation",
 *             period: {
 *                 startedAt: new Date("2024-01-15T09:30:00.000Z")
 *             }
 *         }
 *     }
 */
export interface RequestInteractionCreate {
    /** A unique identifier for the medical professional responsible for this interaction. If nulled, automatically set to a uuid. */
    assignedUserId?: Corti.Uuid;
    /** Details about the encounter. */
    encounter: Corti.Encounter;
    /** Optional patient details. */
    patient?: Corti.Patient;
}
