/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const InteractionsListRequestDirection: core.serialization.Schema<
    serializers.InteractionsListRequestDirection.Raw,
    Corti.InteractionsListRequestDirection
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace InteractionsListRequestDirection {
    export type Raw = "asc" | "desc";
}
