// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { TranscriptsFormatting } from "../../../../types/TranscriptsFormatting.js";
import { TranscriptsParticipant } from "../../../../types/TranscriptsParticipant.js";
import { Uuid } from "../../../../types/Uuid.js";
import { TranscriptsCreateRequestKeyterms } from "../../types/TranscriptsCreateRequestKeyterms.js";
import { TranscriptsCreateRequestReplacementsItem } from "../../types/TranscriptsCreateRequestReplacementsItem.js";
import { TranscriptsCreateRequestWordLevel } from "../../types/TranscriptsCreateRequestWordLevel.js";

export const TranscriptsCreateRequest: core.serialization.Schema<
    serializers.TranscriptsCreateRequest.Raw,
    Corti.TranscriptsCreateRequest
> = core.serialization.object({
    recordingId: Uuid,
    primaryLanguage: core.serialization.string(),
    spokenPunctuation: core.serialization.boolean().optional(),
    automaticPunctuation: core.serialization.boolean().optional(),
    formatting: TranscriptsFormatting.optional(),
    isDictation: core.serialization.boolean().optional(),
    isMultichannel: core.serialization.boolean().optional(),
    diarize: core.serialization.boolean().optional(),
    participants: core.serialization.list(TranscriptsParticipant).optional(),
    async: core.serialization.boolean().optional(),
    replacements: core.serialization.list(TranscriptsCreateRequestReplacementsItem).optional(),
    keyterms: TranscriptsCreateRequestKeyterms.optional(),
    wordLevel: TranscriptsCreateRequestWordLevel.optional(),
});

export declare namespace TranscriptsCreateRequest {
    export interface Raw {
        recordingId: Uuid.Raw;
        primaryLanguage: string;
        spokenPunctuation?: boolean | null;
        automaticPunctuation?: boolean | null;
        formatting?: TranscriptsFormatting.Raw | null;
        isDictation?: boolean | null;
        isMultichannel?: boolean | null;
        diarize?: boolean | null;
        participants?: TranscriptsParticipant.Raw[] | null;
        async?: boolean | null;
        replacements?: TranscriptsCreateRequestReplacementsItem.Raw[] | null;
        keyterms?: TranscriptsCreateRequestKeyterms.Raw | null;
        wordLevel?: TranscriptsCreateRequestWordLevel.Raw | null;
    }
}
