/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { TranscriptsCreateRequestModelName } from "../../types/TranscriptsCreateRequestModelName.js";
import { TranscriptsParticipant } from "../../../../types/TranscriptsParticipant.js";
import { Uuid } from "../../../../types/Uuid.js";

export const TranscriptsCreateRequest: core.serialization.Schema<
    serializers.TranscriptsCreateRequest.Raw,
    Corti.TranscriptsCreateRequest
> = core.serialization.object({
    diarize: core.serialization.boolean().optional(),
    isDictation: core.serialization.boolean().optional(),
    isMultichannel: core.serialization.boolean().optional(),
    modelName: TranscriptsCreateRequestModelName,
    participants: core.serialization.list(TranscriptsParticipant).optional(),
    primaryLanguage: core.serialization.string(),
    recordingId: Uuid,
});

export declare namespace TranscriptsCreateRequest {
    export interface Raw {
        diarize?: boolean | null;
        isDictation?: boolean | null;
        isMultichannel?: boolean | null;
        modelName: TranscriptsCreateRequestModelName.Raw;
        participants?: TranscriptsParticipant.Raw[] | null;
        primaryLanguage: string;
        recordingId: Uuid.Raw;
    }
}
