/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { V2SourceEnum } from "../../../../types/V2SourceEnum.js";

export const FactsUpdateRequest: core.serialization.Schema<
    serializers.FactsUpdateRequest.Raw,
    Corti.FactsUpdateRequest
> = core.serialization.object({
    text: core.serialization.string().optional(),
    group: core.serialization.string().optional(),
    source: V2SourceEnum.optional(),
    isDiscarded: core.serialization.boolean().optional(),
});

export declare namespace FactsUpdateRequest {
    export interface Raw {
        text?: string | null;
        group?: string | null;
        source?: V2SourceEnum.Raw | null;
        isDiscarded?: boolean | null;
    }
}
