/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { CommonSourceEnum } from "../../../../types/CommonSourceEnum.js";

export const FactsUpdateRequest: core.serialization.Schema<
    serializers.FactsUpdateRequest.Raw,
    Corti.FactsUpdateRequest
> = core.serialization.object({
    text: core.serialization.string(),
    group: core.serialization.string().optional(),
    source: CommonSourceEnum,
    isDiscarded: core.serialization.boolean().optional(),
});

export declare namespace FactsUpdateRequest {
    export interface Raw {
        text: string;
        group?: string | null;
        source: CommonSourceEnum.Raw;
        isDiscarded?: boolean | null;
    }
}
