/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { RequestFactsCreateFactsItem } from "../../types/RequestFactsCreateFactsItem.js";

export const RequestFactsCreate: core.serialization.Schema<
    serializers.RequestFactsCreate.Raw,
    Corti.RequestFactsCreate
> = core.serialization.object({
    facts: core.serialization.list(RequestFactsCreateFactsItem),
});

export declare namespace RequestFactsCreate {
    export interface Raw {
        facts: RequestFactsCreateFactsItem.Raw[];
    }
}
