// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Optional filter to restrict the set of codes the model can predict.
 */
export interface CodesFilter {
    /** Condition objects to include. When empty, the full set of codes for the requested systems is used. */
    include?: Corti.CodesFilterCondition[];
    /** Condition objects to subtract from the include set. */
    exclude?: Corti.CodesFilterCondition[];
}
