// This file was auto-generated by Fern from our API Definition.

/** Comparison operator: `=` (equal), `is-a` (code plus descendants), `descendent-of` (strict descendants), `exists` (`value: true`/`false` for set/unset), `in` (membership). */
export const CodesFilterConditionOp = {
    EqualTo: "=",
    IsA: "is-a",
    DescendentOf: "descendent-of",
    Exists: "exists",
    In: "in",
} as const;
export type CodesFilterConditionOp = (typeof CodesFilterConditionOp)[keyof typeof CodesFilterConditionOp];
