/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CommonTranscript {
    /** The channel associated with this phrase/utterance. */
    channel: number;
    /** End time in milliseconds for phrase/utterance. */
    end: number;
    /** The identifier of the participant. */
    participant: number;
    /** Id to tag an identified speaker. Auto-increments. */
    speakerId: number;
    /** Start time in milliseconds for phrase/utterance. */
    start: number;
    /** The spoken phrase or utterance extracted from the audio. */
    text: string;
}
