/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Role of the participant
 */
export type ConfigParticipantRole = "doctor" | "patient" | "multiple";
export const ConfigParticipantRole = {
    Doctor: "doctor",
    Patient: "patient",
    Multiple: "multiple",
} as const;
