/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Processing mode
 */
export type ConfigModeType = "facts" | "transcription";
export const ConfigModeType = {
    Facts: "facts",
    Transcription: "transcription",
} as const;
