/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConfigParticipantRole = "patient" | "doctor" | "multiple";
export const ConfigParticipantRole = {
    Patient: "patient",
    Doctor: "doctor",
    Multiple: "multiple",
} as const;
