/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConfigTranscriptionPrimaryLanguage =
    | "en"
    | "en-us"
    | "en-gb"
    | "da"
    | "se"
    | "no"
    | "de"
    | "nl"
    | "es"
    | "it"
    | "fr"
    | "pt"
    | "de-ch"
    | "sv";
export const ConfigTranscriptionPrimaryLanguage = {
    En: "en",
    EnUs: "en-us",
    EnGb: "en-gb",
    Da: "da",
    Se: "se",
    No: "no",
    De: "de",
    Nl: "nl",
    Es: "es",
    It: "it",
    Fr: "fr",
    Pt: "pt",
    DeCh: "de-ch",
    Sv: "sv",
} as const;
