/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface ConfigStatus {
    /** Configuration status result */
    type: Corti.ConfigStatusType;
    /** Optional reason for rejection (e.g., 'language unavailable') */
    reason?: string;
}
