/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface DocumentsCreateRequestWithTemplateKey {
    /** An array of context objects. */
    context: Corti.DocumentsContext[];
    /** The key of the template that informs on what kind of document is to be generated. */
    templateKey: string;
    /** An optional name for the document. */
    name?: string;
    /** The model or documentation mode to use for summarization. */
    modelName?: string;
    /** The language in which the document will be generated. Check https://docs.corti.ai/about/languages for more. */
    outputLanguage: string;
}
