/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export type DocumentsCreateRequest =
    | Corti.DocumentsCreateRequestWithTemplateKey
    | Corti.DocumentsCreateRequestWithTemplateId
    | Corti.DocumentsCreateRequestWithTemplate;
