/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export type DocumentsContextData =
    /**
     * Facts */
    | Corti.FactContext[]
    /**
     * Transcript */
    | Corti.Transcript
    /**
     * Text */
    | string;
