/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface DocumentsContext {
    /** The type of context data. */
    type: Corti.DocumentsContextTypeEnum;
    /** The actual data, which can be an array of facts, a transcript, or a string. */
    data?: Corti.DocumentsContextData;
}
