/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface EncounterUpdate {
    /** A unique identifier for the encounter. */
    identifier?: string;
    /** The current status of the encounter. */
    status?: Corti.EncounterStatus;
    /** The type of encounter. */
    type?: Corti.EncounterType;
    /** Details of when the encounter took place, including start and optional end timestamps with timezone offsets. */
    period?: Corti.EncounterPeriod;
    /** A title providing context about the encounter. */
    title?: string;
}
