/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface FactsListResponseFactsItem {
    /** The unique identifier of the fact. */
    id?: Corti.Uuid;
    /** The text content of the fact. */
    text?: string;
    /** The key identifying the group to which the fact belongs. */
    group?: string;
    /** The unique identifier of the group to which the fact belongs. */
    groupId?: Corti.Uuid;
    /** Indicates whether the fact has been marked as discarded. */
    isDiscarded?: boolean;
    /** The origin of the fact. */
    source?: Corti.CommonSourceEnum;
    /** The timestamp when the fact was created. */
    createdAt?: Date;
    /** The timestamp when the fact was last updated. */
    updatedAt?: Date;
    evidence?: Corti.FactsListResponseFactsItemEvidenceItem[];
}
