/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Fact {
    /** Unique identifier for the fact */
    id: string;
    /** Text description of the fact */
    text: string;
    /** Categorization of the fact (e.g., medical-history) */
    group: string;
    /** Unique identifier for the group */
    groupId: string;
    /** Indicates if the fact was discarded */
    isDiscarded: boolean;
    /** Source of the fact (e.g., core for generated automatically) */
    source: string;
    /** Timestamp when the fact was created */
    createdAt?: string;
    /** Timestamp when the fact was last updated */
    updatedAt?: string;
}
