/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface FactsListResponse {
    /** A list of facts associated with the interaction. */
    facts: Corti.FactsListItem[];
}
