/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FactsFactGroupsListResponseDataItemTranslationsItem {
    id?: number;
    languagesId?: string;
    name?: string;
}
