/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GenderEnum = "male" | "female" | "unknown" | "other";
export const GenderEnum = {
    Male: "male",
    Female: "female",
    Unknown: "unknown",
    Other: "other",
} as const;
