/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InteractionsEncounterTypeEnum =
    | "first_consultation"
    | "consultation"
    | "emergency"
    | "inpatient"
    | "outpatient";
export const InteractionsEncounterTypeEnum = {
    FirstConsultation: "first_consultation",
    Consultation: "consultation",
    Emergency: "emergency",
    Inpatient: "inpatient",
    Outpatient: "outpatient",
} as const;
