/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface InteractionsEncounterUpdateRequest {
    /** A unique identifier for the encounter. */
    identifier?: string;
    /** The current status of the encounter. */
    status?: Corti.InteractionsEncounterStatusEnum;
    /** The type of encounter. */
    type?: Corti.InteractionsEncounterTypeEnum;
    /** Details of when the encounter took place, including start and optional end timestamps with timezone offsets. */
    period?: Corti.InteractionsEncounterPeriod;
    /** A title providing context about the encounter. */
    title?: string | null;
}
