/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InteractionsEncounterPeriod {
    /** The start date/time of the encounter. (UTC) */
    startedAt: Date;
    /** The end date/time of the encounter. (UTC) */
    endedAt?: Date;
}
