/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InteractionsEncounterStatusEnum =
    | "planned"
    | "in-progress"
    | "on-hold"
    | "completed"
    | "cancelled"
    | "deleted";
export const InteractionsEncounterStatusEnum = {
    Planned: "planned",
    InProgress: "in-progress",
    OnHold: "on-hold",
    Completed: "completed",
    Cancelled: "cancelled",
    Deleted: "deleted",
} as const;
