/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface InteractionsEncounterUpdateRequest {
    /** A unique identifier for the encounter, essential for tracking and referencing specific patient interactions. */
    identifier?: string;
    /** Indicates the current state of the encounter, crucial for understanding the progression and current state of care. */
    status?: Corti.InteractionsEncounterStatusEnum;
    /** The specific type of encounter, providing context about the nature and setting of the patient interaction. */
    type?: Corti.InteractionsEncounterTypeEnum;
    /** The time period during which the encounter takes place. */
    period?: Corti.InteractionsEncounterPeriod;
    /** A readable name for the interaction */
    title?: string | null;
}
