/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface RecordingsListResponse {
    /** A list of recordings for the interaction. */
    recordings: Corti.Uuid[];
}
