/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RequestEncounterPeriodUpdate {
    /** The UTC timestamp indicating when the encounter started. */
    startedAt: Date;
    /** The UTC timestamp indicating when the encounter ended. */
    endedAt?: Date;
}
