/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface ResponseAllTemplateSections {
    /** List of filtered template sections */
    data?: Corti.Section[];
}
