/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface ResponseAllTemplatesDataItem {
    /** The timestamp when the template was updated. */
    date_updated?: string;
    /** Name of the template */
    name?: string;
    /** Description of the template */
    description?: string;
    /** Unique key for the template */
    key?: string;
    /** Status of the template. */
    status?: string;
    /** List of sections included in the template */
    template_sections?: Corti.ResponseAllTemplatesDataItemTemplateSectionsItem[];
    /** Available translations for the template */
    translations?: Corti.ResponseAllTemplatesDataItemTranslationsItem[];
}
