/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface ResponseTranscriptCreate {
    /** The unique identifier of the transcript. */
    id?: Corti.Uuid;
    /** Additional information about the participants involved in the transcript. */
    metadata?: Corti.ResponseMetadataCreate;
    /** An array of transcripts. */
    transcripts?: Corti.Transcript[];
    usageInfo?: Corti.UsageInfo;
    /** The unique identifier of the related recording. */
    recordingId?: Corti.Uuid;
}
