/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SectionTranslationsItem {
    /** Language identifier */
    languages_id?: string;
    /** Localized name of the section */
    name?: string;
    /** Localized description of the section */
    description?: string;
}
