/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface StreamConfigTranscription {
    /** Primary spoken language for transcription */
    primaryLanguage: Corti.StreamSupportedLanguage;
    /** Enable speaker diarization */
    isDiarization?: boolean;
    /** Enable multi-channel audio processing */
    isMultichannel?: boolean;
    /** List of participants with roles assigned to a channel */
    participants: Corti.StreamConfigParticipant[];
}
