/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Role of the participant (e.g., doctor, patient, or multiple)
 */
export type StreamConfigParticipantRole = "doctor" | "patient" | "multiple";
export const StreamConfigParticipantRole = {
    Doctor: "doctor",
    Patient: "patient",
    Multiple: "multiple",
} as const;
