/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Processing mode
 */
export type StreamConfigModeType = "facts" | "transcription" | "documentation";
export const StreamConfigModeType = {
    Facts: "facts",
    Transcription: "transcription",
    Documentation: "documentation",
} as const;
