/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TemplatesTranslation {
    /** Language identifier */
    languagesId: string;
    /** Localized name */
    name?: string;
    /** Localized description */
    description?: string;
}
