/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface TemplatesListResponseDataItem {
    /** The timestamp when the template was updated. */
    dateUpdated?: Date | null;
    /** Name of the template */
    name: string;
    /** Description of the template */
    description: string;
    /** Unique key for the template */
    key: string;
    /** Status of the template. */
    status: string;
    /** List of sections included in the template */
    templateSections: Corti.TemplatesListResponseDataItemTemplateSectionsItem[];
    /** Available translations for the template */
    translations: Corti.TemplatesListResponseDataItemTranslationsItem[];
}
