/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TemplatesItemTranslationsItem {
    /** Language identifier */
    languagesId: string;
    /** Localized name of the template */
    name?: string;
    /** Localized description of the template */
    description?: string;
}
