// This file was auto-generated by Fern from our API Definition.

/** Formatting for ordinals. */
export const TranscriptsFormattingOrdinals = {
    NumeralsAboveNine: "numerals_above_nine",
    AsDictated: "as_dictated",
    Numerals: "numerals",
} as const;
export type TranscriptsFormattingOrdinals =
    (typeof TranscriptsFormattingOrdinals)[keyof typeof TranscriptsFormattingOrdinals];
