/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TranscribeErrorMessageError {
    /** Unique error identifier */
    id: string;
    /** Error title */
    title: string;
    /** HTTP status code */
    status: number;
    /** Detailed error description */
    details: string;
    /** Link to documentation */
    doc: string;
}
