/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface TranscriptsParticipant {
    /** The audio channel associated with the participant. */
    channel: number;
    /** The role of the participant. */
    role: Corti.TranscriptParticipantRoleEnum;
}
