/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface TranscriptsData {
    /** Additional information about the participants involved in the transcript. */
    metadata: Corti.TranscriptsMetadata;
    /** An array of transcripts. */
    transcripts: Corti.TranscriptsDataTranscriptsItem[];
}
