/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TranscriptsParticipantRoleEnum = "doctor" | "patient" | "multiple";
export const TranscriptsParticipantRoleEnum = {
    Doctor: "doctor",
    Patient: "patient",
    Multiple: "multiple",
} as const;
