// This file was auto-generated by Fern from our API Definition.

/** Formatting for times. */
export const TranscriptsFormattingTimes = {
    Locale: "locale",
    H24: "h24",
    H12: "h12",
    AsDictated: "as_dictated",
} as const;
export type TranscriptsFormattingTimes = (typeof TranscriptsFormattingTimes)[keyof typeof TranscriptsFormattingTimes];
