/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UsageMessage {
    type: "usage";
    /** The amount of credits used for this stream. */
    credits: number;
}
