/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type V2DocumentContextTypeEnum = "facts" | "transcript" | "string";
export const V2DocumentContextTypeEnum = {
    Facts: "facts",
    Transcript: "transcript",
    String: "string",
} as const;
