/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         facts: [{
 *                 group: "other",
 *                 text: "text"
 *             }]
 *     }
 */
export interface FactsCreateRequest {
    /** A list of facts to be created. */
    facts: Corti.FactsCreateInput[];
}
