/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         facts: [{
 *                 factId: "factId"
 *             }]
 *     }
 */
export interface FactsBatchUpdateRequest {
    /** A list of facts to be updated. */
    facts: Corti.FactsBatchUpdateRequestFactsItem[];
}
