/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface FactsUpdateRequest {
    /** The updated group key for the fact. */
    group?: string;
    /** Indicates whether the fact should be marked as discarded. */
    isDiscarded?: boolean;
    /** The updated origin of the fact. */
    source?: Corti.CommonSourceEnum;
    /** The updated text of the fact. */
    text?: string;
}
