/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as qs from "qs";
import { StreamSocket } from "./Socket.js";

export declare namespace Stream {
    export interface Options {
        environment?: core.Supplier<environments.CortiEnvironment | environments.CortiEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the Tenant-Name header */
        tenantName: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface ConnectArgs {
        id: string;
        token?: string;
        tenantName?: string;
        /** Arbitrary headers to send with the websocket connect request. */
        headers?: Record<string, unknown>;
        /** Enable debug mode on the websocket. Defaults to false. */
        debug?: boolean;
        /** Number of reconnect attempts. Defaults to 30. */
        reconnectAttempts?: number;
    }
}

export class Stream {
    protected readonly _options: Stream.Options;

    constructor(_options: Stream.Options) {
        this._options = _options;
    }

    public async connect(args: Stream.ConnectArgs): Promise<StreamSocket> {
        const queryParams: Record<string, unknown> = {};
        if (args["token"] != null) {
            queryParams["token"] = args["token"];
        }

        if (args["tenantName"] != null) {
            queryParams["tenantName"] = args["tenantName"];
        }

        let websocketHeaders: Record<string, unknown> = {};
        websocketHeaders = {
            ...websocketHeaders,
            ...args["headers"],
        };
        const socket = new core.ReconnectingWebSocket(
            `${(await core.Supplier.get(this._options["baseUrl"])) ?? ((await core.Supplier.get(this._options["environment"])) ?? environments.CortiEnvironment.BetaEu).wss}/audio-bridge/v2/interactions/?${encodeURIComponent(args["id"])}/streams${qs.stringify(queryParams, { arrayFormat: "repeat" })}`,
            [],
            { debug: args["debug"] ?? false, maxRetries: args["reconnectAttempts"] ?? 30 },
            websocketHeaders,
        );
        return new StreamSocket({ socket });
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
