/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sorting order. Allowed values: [asc, desc]. Default is desc.
 */
export type InteractionsListRequestDirection = "asc" | "desc";
export const InteractionsListRequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
