// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../index.js";

/**
 * @example
 *     {
 *         name: "coder",
 *         description: "Returns ICD-10 codes for a clinical encounter.",
 *         systemPrompt: "Respond with only the ICD-10 code.",
 *         model: "corti-default",
 *         visibility: "private",
 *         lifecycle: "persistent",
 *         connectors: [{
 *                 type: "registry",
 *                 name: "pubmed-expert"
 *             }, {
 *                 type: "mcp",
 *                 name: "policybot",
 *                 url: "https://mcp.example.com",
 *                 auth: {
 *                     type: "oauth2",
 *                     scope: "read:policies",
 *                     redirectUrl: "https://app.corti.ai/oauth/callback"
 *                 }
 *             }, {
 *                 type: "schema",
 *                 name: "submit_code",
 *                 description: "Submit the final ICD-10 code for the encounter along with a confidence score.",
 *                 schema: {
 *                     "type": "object",
 *                     "properties": {
 *                         "code": {
 *                             "type": "string",
 *                             "description": "The selected ICD-10 code."
 *                         },
 *                         "confidence": {
 *                             "type": "number",
 *                             "minimum": 0,
 *                             "maximum": 1
 *                         }
 *                     },
 *                     "required": [
 *                         "code"
 *                     ]
 *                 },
 *                 transition: "complete"
 *             }],
 *         labels: {
 *             "team": "coding",
 *             "env": "prod"
 *         }
 *     }
 */
export interface AgenticAgentsCreateRequest {
    /** Human-readable, unique-per-tenant agent name. */
    name: string;
    /** Free-form agent description. */
    description?: string;
    /** System prompt prepended to every invocation. */
    systemPrompt?: string;
    /** Tenant default if omitted. */
    model?: string;
    /** Caps the orchestrator's ReAct loop iterations per run. Server default 10 if omitted. */
    maxLoops?: number;
    visibility?: Corti.AgentsVisibility;
    lifecycle?: Corti.AgentsLifecycle;
    /** Connectors to attach at creation. Defaults to an empty array. */
    connectors?: Corti.CommonConnectorCreateRequest[];
    labels?: Corti.AgentsLabels;
}
