// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentsCreateMcpServerAuthorizationType } from "./AgentsCreateMcpServerAuthorizationType.js";
import { AgentsCreateMcpServerTransportType } from "./AgentsCreateMcpServerTransportType.js";

export const AgentsCreateMcpServer: core.serialization.ObjectSchema<
    serializers.AgentsCreateMcpServer.Raw,
    Corti.AgentsCreateMcpServer
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    transportType: AgentsCreateMcpServerTransportType,
    authorizationType: AgentsCreateMcpServerAuthorizationType,
    authorizationScope: core.serialization.string().optional(),
    url: core.serialization.string(),
    redirectUrl: core.serialization.string().optional(),
    token: core.serialization.string().optional(),
    requiredHeaders: core.serialization.list(core.serialization.string()).optional(),
    optionalHeaders: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AgentsCreateMcpServer {
    export interface Raw {
        name: string;
        description?: string | null;
        transportType: AgentsCreateMcpServerTransportType.Raw;
        authorizationType: AgentsCreateMcpServerAuthorizationType.Raw;
        authorizationScope?: string | null;
        url: string;
        redirectUrl?: string | null;
        token?: string | null;
        requiredHeaders?: string[] | null;
        optionalHeaders?: string[] | null;
    }
}
