// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentsMcpServerAuthorizationType } from "./AgentsMcpServerAuthorizationType.js";
import { AgentsMcpServerTransportType } from "./AgentsMcpServerTransportType.js";

export const AgentsMcpServer: core.serialization.ObjectSchema<serializers.AgentsMcpServer.Raw, Corti.AgentsMcpServer> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        transportType: AgentsMcpServerTransportType,
        authorizationType: AgentsMcpServerAuthorizationType,
        authorizationScope: core.serialization.string().optional(),
        url: core.serialization.string(),
        redirectUrl: core.serialization.string().optionalNullable(),
        requiredHeaders: core.serialization.list(core.serialization.string()).optional(),
        optionalHeaders: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace AgentsMcpServer {
    export interface Raw {
        id: string;
        name: string;
        transportType: AgentsMcpServerTransportType.Raw;
        authorizationType: AgentsMcpServerAuthorizationType.Raw;
        authorizationScope?: string | null;
        url: string;
        redirectUrl?: (string | null | undefined) | null;
        requiredHeaders?: string[] | null;
        optionalHeaders?: string[] | null;
    }
}
