/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const AudioPacket: core.serialization.ObjectSchema<serializers.AudioPacket.Raw, Corti.AudioPacket> =
    core.serialization.object({
        timestamp: core.serialization.date().optional(),
        data: core.serialization.string().optional(),
    });

export declare namespace AudioPacket {
    export interface Raw {
        timestamp?: string | null;
        data?: string | null;
    }
}
