// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CodesFilterConditionOp: core.serialization.Schema<
    serializers.CodesFilterConditionOp.Raw,
    Corti.CodesFilterConditionOp
> = core.serialization.enum_(["=", "is-a", "descendent-of", "exists", "in"]);

export declare namespace CodesFilterConditionOp {
    export type Raw = "=" | "is-a" | "descendent-of" | "exists" | "in";
}
