// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CodesFilterCondition } from "./CodesFilterCondition.js";

export const CodesFilter: core.serialization.ObjectSchema<serializers.CodesFilter.Raw, Corti.CodesFilter> =
    core.serialization.object({
        include: core.serialization.list(CodesFilterCondition).optional(),
        exclude: core.serialization.list(CodesFilterCondition).optional(),
    });

export declare namespace CodesFilter {
    export interface Raw {
        include?: CodesFilterCondition.Raw[] | null;
        exclude?: CodesFilterCondition.Raw[] | null;
    }
}
