// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonConnectorAuthType } from "./CommonConnectorAuthType.js";

export const CommonConnectorAuth: core.serialization.ObjectSchema<
    serializers.CommonConnectorAuth.Raw,
    Corti.CommonConnectorAuth
> = core.serialization.object({
    type: CommonConnectorAuthType,
    scope: core.serialization.string().optional(),
    redirectUrl: core.serialization.string().optional(),
    ref: core.serialization.string().optional(),
    requiredHeaders: core.serialization.list(core.serialization.string()).optional(),
    optionalHeaders: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace CommonConnectorAuth {
    export interface Raw {
        type: CommonConnectorAuthType.Raw;
        scope?: string | null;
        redirectUrl?: string | null;
        ref?: string | null;
        requiredHeaders?: string[] | null;
        optionalHeaders?: string[] | null;
    }
}
