/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const CommonSourceEnum: core.serialization.Schema<serializers.CommonSourceEnum.Raw, Corti.CommonSourceEnum> =
    core.serialization.enum_(["core", "system", "user"]);

export declare namespace CommonSourceEnum {
    export type Raw = "core" | "system" | "user";
}
