/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const CommonSortingDirectionEnum: core.serialization.Schema<
    serializers.CommonSortingDirectionEnum.Raw,
    Corti.CommonSortingDirectionEnum
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace CommonSortingDirectionEnum {
    export type Raw = "asc" | "desc";
}
