/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const CommonUsageInfo: core.serialization.ObjectSchema<serializers.CommonUsageInfo.Raw, Corti.CommonUsageInfo> =
    core.serialization.object({
        creditsConsumed: core.serialization.number(),
    });

export declare namespace CommonUsageInfo {
    export interface Raw {
        creditsConsumed: number;
    }
}
