/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const DocumentsSectionInput: core.serialization.ObjectSchema<
    serializers.DocumentsSectionInput.Raw,
    Corti.DocumentsSectionInput
> = core.serialization.object({
    key: core.serialization.string(),
    name: core.serialization.string().optional(),
    text: core.serialization.string().optional(),
    sort: core.serialization.number().optional(),
});

export declare namespace DocumentsSectionInput {
    export interface Raw {
        key: string;
        name?: string | null;
        text?: string | null;
        sort?: number | null;
    }
}
