/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsContext } from "./DocumentsContext.js";
import { Uuid } from "./Uuid.js";

export const DocumentsCreateRequestWithTemplateId: core.serialization.ObjectSchema<
    serializers.DocumentsCreateRequestWithTemplateId.Raw,
    Corti.DocumentsCreateRequestWithTemplateId
> = core.serialization.object({
    context: core.serialization.list(DocumentsContext),
    modelName: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    outputLanguage: core.serialization.string(),
    templateId: Uuid,
});

export declare namespace DocumentsCreateRequestWithTemplateId {
    export interface Raw {
        context: DocumentsContext.Raw[];
        modelName?: string | null;
        name?: string | null;
        outputLanguage: string;
        templateId: Uuid.Raw;
    }
}
