/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { FactsContext } from "./FactsContext.js";
import { Transcript } from "./Transcript.js";

export const DocumentsContextData: core.serialization.Schema<
    serializers.DocumentsContextData.Raw,
    Corti.DocumentsContextData
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(FactsContext),
    Transcript,
    core.serialization.string(),
]);

export declare namespace DocumentsContextData {
    export type Raw = FactsContext.Raw[] | Transcript.Raw | string;
}
