/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const DocumentsContextTypeEnum: core.serialization.Schema<
    serializers.DocumentsContextTypeEnum.Raw,
    Corti.DocumentsContextTypeEnum
> = core.serialization.enum_(["facts", "transcript", "string"]);

export declare namespace DocumentsContextTypeEnum {
    export type Raw = "facts" | "transcript" | "string";
}
