/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsContext } from "./DocumentsContext.js";
import { DocumentsTemplate } from "./DocumentsTemplate.js";

export const DocumentsCreateRequestWithTemplate: core.serialization.ObjectSchema<
    serializers.DocumentsCreateRequestWithTemplate.Raw,
    Corti.DocumentsCreateRequestWithTemplate
> = core.serialization.object({
    context: core.serialization.list(DocumentsContext),
    template: DocumentsTemplate,
    name: core.serialization.string().optional(),
    modelName: core.serialization.string().optional(),
    outputLanguage: core.serialization.string(),
});

export declare namespace DocumentsCreateRequestWithTemplate {
    export interface Raw {
        context: DocumentsContext.Raw[];
        template: DocumentsTemplate.Raw;
        name?: string | null;
        modelName?: string | null;
        outputLanguage: string;
    }
}
