/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { DocumentsSection } from "./DocumentsSection.js";
import { CommonUsageInfo } from "./CommonUsageInfo.js";

export const DocumentsGetResponse: core.serialization.ObjectSchema<
    serializers.DocumentsGetResponse.Raw,
    Corti.DocumentsGetResponse
> = core.serialization.object({
    createdAt: core.serialization.date(),
    id: Uuid,
    isStream: core.serialization.boolean(),
    name: core.serialization.string(),
    outputLanguage: core.serialization.string(),
    sections: core.serialization.list(DocumentsSection),
    templateRef: core.serialization.string(),
    updatedAt: core.serialization.date(),
    usageInfo: CommonUsageInfo,
});

export declare namespace DocumentsGetResponse {
    export interface Raw {
        createdAt: string;
        id: Uuid.Raw;
        isStream: boolean;
        name: string;
        outputLanguage: string;
        sections: DocumentsSection.Raw[];
        templateRef: string;
        updatedAt: string;
        usageInfo: CommonUsageInfo.Raw;
    }
}
