/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsContextData } from "./DocumentsContextData.js";
import { DocumentsContextTypeEnum } from "./DocumentsContextTypeEnum.js";

export const DocumentsContext: core.serialization.ObjectSchema<
    serializers.DocumentsContext.Raw,
    Corti.DocumentsContext
> = core.serialization.object({
    data: DocumentsContextData,
    type: DocumentsContextTypeEnum,
});

export declare namespace DocumentsContext {
    export interface Raw {
        data: DocumentsContextData.Raw;
        type: DocumentsContextTypeEnum.Raw;
    }
}
