/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { EncounterStatus } from "./EncounterStatus.js";
import { EncounterType } from "./EncounterType.js";
import { EncounterPeriod } from "./EncounterPeriod.js";

export const EncounterUpdate: core.serialization.ObjectSchema<serializers.EncounterUpdate.Raw, Corti.EncounterUpdate> =
    core.serialization.object({
        identifier: core.serialization.string().optional(),
        status: EncounterStatus.optional(),
        type: EncounterType.optional(),
        period: EncounterPeriod.optional(),
        title: core.serialization.string().optional(),
    });

export declare namespace EncounterUpdate {
    export interface Raw {
        identifier?: string | null;
        status?: EncounterStatus.Raw | null;
        type?: EncounterType.Raw | null;
        period?: EncounterPeriod.Raw | null;
        title?: string | null;
    }
}
