/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const EncounterStatus: core.serialization.Schema<serializers.EncounterStatus.Raw, Corti.EncounterStatus> =
    core.serialization.enum_(["planned", "in-progress", "on-hold", "completed", "cancelled", "deleted"]);

export declare namespace EncounterStatus {
    export type Raw = "planned" | "in-progress" | "on-hold" | "completed" | "cancelled" | "deleted";
}
