/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { V2EncounterStatusEnum } from "./V2EncounterStatusEnum.js";
import { V2EncounterTypeEnum } from "./V2EncounterTypeEnum.js";
import { EncounterPeriod } from "./EncounterPeriod.js";

export const Encounter: core.serialization.ObjectSchema<serializers.Encounter.Raw, Corti.Encounter> =
    core.serialization.object({
        identifier: core.serialization.string(),
        status: V2EncounterStatusEnum,
        type: V2EncounterTypeEnum,
        period: EncounterPeriod,
        title: core.serialization.string().optional(),
    });

export declare namespace Encounter {
    export interface Raw {
        identifier: string;
        status: V2EncounterStatusEnum.Raw;
        type: V2EncounterTypeEnum.Raw;
        period: EncounterPeriod.Raw;
        title?: string | null;
    }
}
