/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, Corti.ErrorResponse> =
    core.serialization.object({
        requestid: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
        status: core.serialization.number().optional(),
        title: core.serialization.string().optional(),
        details: core.serialization.string().optional(),
        instance: core.serialization.string().optional(),
    });

export declare namespace ErrorResponse {
    export interface Raw {
        requestid?: string | null;
        type?: string | null;
        status?: number | null;
        title?: string | null;
        details?: string | null;
        instance?: string | null;
    }
}
