/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const FactsEvidence: core.serialization.ObjectSchema<serializers.FactsEvidence.Raw, Corti.FactsEvidence> =
    core.serialization.object({
        type: core.serialization.string().optional(),
        reference: core.serialization.string().optional(),
        quote: core.serialization.string().optional(),
    });

export declare namespace FactsEvidence {
    export interface Raw {
        type?: string | null;
        reference?: string | null;
        quote?: string | null;
    }
}
