/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { CommonSourceEnum } from "./CommonSourceEnum.js";

export const FactsCreateInput: core.serialization.ObjectSchema<
    serializers.FactsCreateInput.Raw,
    Corti.FactsCreateInput
> = core.serialization.object({
    text: core.serialization.string(),
    group: core.serialization.string(),
    source: CommonSourceEnum.optional(),
});

export declare namespace FactsCreateInput {
    export interface Raw {
        text: string;
        group: string;
        source?: CommonSourceEnum.Raw | null;
    }
}
