/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { CommonSourceEnum } from "./CommonSourceEnum.js";

export const FactsUpdateResponse: core.serialization.ObjectSchema<
    serializers.FactsUpdateResponse.Raw,
    Corti.FactsUpdateResponse
> = core.serialization.object({
    id: Uuid,
    text: core.serialization.string(),
    group: core.serialization.string(),
    groupId: Uuid,
    source: CommonSourceEnum,
    isDiscarded: core.serialization.boolean(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});

export declare namespace FactsUpdateResponse {
    export interface Raw {
        id: Uuid.Raw;
        text: string;
        group: string;
        groupId: Uuid.Raw;
        source: CommonSourceEnum.Raw;
        isDiscarded: boolean;
        createdAt: string;
        updatedAt: string;
    }
}
