/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { FactsCreateItem } from "./FactsCreateItem.js";

export const FactsCreateResponse: core.serialization.ObjectSchema<
    serializers.FactsCreateResponse.Raw,
    Corti.FactsCreateResponse
> = core.serialization.object({
    facts: core.serialization.list(FactsCreateItem),
});

export declare namespace FactsCreateResponse {
    export interface Raw {
        facts: FactsCreateItem.Raw[];
    }
}
