/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { FactsUpdateResponseFactsItem } from "./FactsUpdateResponseFactsItem.js";

export const FactsUpdateResponse: core.serialization.ObjectSchema<
    serializers.FactsUpdateResponse.Raw,
    Corti.FactsUpdateResponse
> = core.serialization.object({
    facts: core.serialization.list(FactsUpdateResponseFactsItem),
});

export declare namespace FactsUpdateResponse {
    export interface Raw {
        facts: FactsUpdateResponseFactsItem.Raw[];
    }
}
