/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { FactsFactGroupsListResponseDataItemTranslationsItem } from "./FactsFactGroupsListResponseDataItemTranslationsItem.js";

export const FactsFactGroupsListResponseDataItem: core.serialization.ObjectSchema<
    serializers.FactsFactGroupsListResponseDataItem.Raw,
    Corti.FactsFactGroupsListResponseDataItem
> = core.serialization.object({
    id: Uuid,
    key: core.serialization.string(),
    translations: core.serialization.list(FactsFactGroupsListResponseDataItemTranslationsItem),
});

export declare namespace FactsFactGroupsListResponseDataItem {
    export interface Raw {
        id: Uuid.Raw;
        key: string;
        translations: FactsFactGroupsListResponseDataItemTranslationsItem.Raw[];
    }
}
