/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { FactGroupsFilteredResponseDataItem } from "./FactGroupsFilteredResponseDataItem.js";

export const FactGroupsFilteredResponse: core.serialization.ObjectSchema<
    serializers.FactGroupsFilteredResponse.Raw,
    Corti.FactGroupsFilteredResponse
> = core.serialization.object({
    data: core.serialization.list(FactGroupsFilteredResponseDataItem),
});

export declare namespace FactGroupsFilteredResponse {
    export interface Raw {
        data: FactGroupsFilteredResponseDataItem.Raw[];
    }
}
