/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { FactsFactGroupsListResponseDataItem } from "./FactsFactGroupsListResponseDataItem.js";

export const FactsFactGroupsListResponse: core.serialization.ObjectSchema<
    serializers.FactsFactGroupsListResponse.Raw,
    Corti.FactsFactGroupsListResponse
> = core.serialization.object({
    data: core.serialization.list(FactsFactGroupsListResponseDataItem),
});

export declare namespace FactsFactGroupsListResponse {
    export interface Raw {
        data: FactsFactGroupsListResponseDataItem.Raw[];
    }
}
