/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { CommonSourceEnum } from "./CommonSourceEnum.js";

export const FactsCreateItem: core.serialization.ObjectSchema<serializers.FactsCreateItem.Raw, Corti.FactsCreateItem> =
    core.serialization.object({
        group: core.serialization.string().optional(),
        groupId: Uuid.optional(),
        id: Uuid.optional(),
        isDiscarded: core.serialization.boolean().optional(),
        source: CommonSourceEnum.optional(),
        text: core.serialization.string().optional(),
        updatedAt: core.serialization.date().optional(),
    });

export declare namespace FactsCreateItem {
    export interface Raw {
        group?: string | null;
        groupId?: Uuid.Raw | null;
        id?: Uuid.Raw | null;
        isDiscarded?: boolean | null;
        source?: CommonSourceEnum.Raw | null;
        text?: string | null;
        updatedAt?: string | null;
    }
}
