/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { CommonSourceEnum } from "./CommonSourceEnum.js";

export const FactContext: core.serialization.ObjectSchema<serializers.FactContext.Raw, Corti.FactContext> =
    core.serialization.object({
        text: core.serialization.string(),
        group: core.serialization.string().optional(),
        source: CommonSourceEnum,
    });

export declare namespace FactContext {
    export interface Raw {
        text: string;
        group?: string | null;
        source: CommonSourceEnum.Raw;
    }
}
