/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { InteractionsGenderEnum } from "./InteractionsGenderEnum.js";

export const InteractionsPatient: core.serialization.ObjectSchema<
    serializers.InteractionsPatient.Raw,
    Corti.InteractionsPatient
> = core.serialization.object({
    identifier: core.serialization.string(),
    name: core.serialization.string().optionalNullable(),
    gender: InteractionsGenderEnum.optional(),
    birthDate: core.serialization.date().optionalNullable(),
    pronouns: core.serialization.string().optionalNullable(),
});

export declare namespace InteractionsPatient {
    export interface Raw {
        identifier: string;
        name?: (string | null) | null;
        gender?: InteractionsGenderEnum.Raw | null;
        birthDate?: (string | null) | null;
        pronouns?: (string | null) | null;
    }
}
