/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const InteractionsGenderEnum: core.serialization.Schema<
    serializers.InteractionsGenderEnum.Raw,
    Corti.InteractionsGenderEnum
> = core.serialization.enum_(["male", "female", "unknown", "other"]);

export declare namespace InteractionsGenderEnum {
    export type Raw = "male" | "female" | "unknown" | "other";
}
