/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";

export const RecordingsCreateResponse: core.serialization.ObjectSchema<
    serializers.RecordingsCreateResponse.Raw,
    Corti.RecordingsCreateResponse
> = core.serialization.object({
    recordingId: Uuid,
});

export declare namespace RecordingsCreateResponse {
    export interface Raw {
        recordingId: Uuid.Raw;
    }
}
