/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const RequestEncounterPeriodUpdate: core.serialization.ObjectSchema<
    serializers.RequestEncounterPeriodUpdate.Raw,
    Corti.RequestEncounterPeriodUpdate
> = core.serialization.object({
    startedAt: core.serialization.date(),
    endedAt: core.serialization.date().optional(),
});

export declare namespace RequestEncounterPeriodUpdate {
    export interface Raw {
        startedAt: string;
        endedAt?: string | null;
    }
}
