/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";

export const ResponseInteractionCreate: core.serialization.ObjectSchema<
    serializers.ResponseInteractionCreate.Raw,
    Corti.ResponseInteractionCreate
> = core.serialization.object({
    interactionId: Uuid.optional(),
    websocketUrl: core.serialization.string().optional(),
});

export declare namespace ResponseInteractionCreate {
    export interface Raw {
        interactionId?: Uuid.Raw | null;
        websocketUrl?: string | null;
    }
}
