/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { ResponseAllTemplatesDataItem } from "./ResponseAllTemplatesDataItem.js";

export const ResponseAllTemplates: core.serialization.ObjectSchema<
    serializers.ResponseAllTemplates.Raw,
    Corti.ResponseAllTemplates
> = core.serialization.object({
    data: core.serialization.list(ResponseAllTemplatesDataItem).optional(),
});

export declare namespace ResponseAllTemplates {
    export interface Raw {
        data?: ResponseAllTemplatesDataItem.Raw[] | null;
    }
}
