/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { ResponseFactGroupsFilteredDataItem } from "./ResponseFactGroupsFilteredDataItem.js";

export const ResponseFactGroupsFiltered: core.serialization.ObjectSchema<
    serializers.ResponseFactGroupsFiltered.Raw,
    Corti.ResponseFactGroupsFiltered
> = core.serialization.object({
    data: core.serialization.list(ResponseFactGroupsFilteredDataItem).optional(),
});

export declare namespace ResponseFactGroupsFiltered {
    export interface Raw {
        data?: ResponseFactGroupsFilteredDataItem.Raw[] | null;
    }
}
