/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Section } from "./Section.js";

export const ResponseAllTemplatesDataItemTemplateSectionsItem: core.serialization.ObjectSchema<
    serializers.ResponseAllTemplatesDataItemTemplateSectionsItem.Raw,
    Corti.ResponseAllTemplatesDataItemTemplateSectionsItem
> = core.serialization.object({
    sort: core.serialization.number().optional(),
    sectionsId: core.serialization.property("sections_id", Section.optional()),
});

export declare namespace ResponseAllTemplatesDataItemTemplateSectionsItem {
    export interface Raw {
        sort?: number | null;
        sections_id?: Section.Raw | null;
    }
}
