/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { V2SourceEnum } from "./V2SourceEnum.js";

export const ResponseFactsUpdateFactsItem: core.serialization.ObjectSchema<
    serializers.ResponseFactsUpdateFactsItem.Raw,
    Corti.ResponseFactsUpdateFactsItem
> = core.serialization.object({
    id: Uuid.optional(),
    text: core.serialization.string().optional(),
    group: core.serialization.string().optional(),
    groupId: Uuid.optional(),
    source: V2SourceEnum.optional(),
    isDiscarded: core.serialization.boolean().optional(),
    createdAt: core.serialization.date().optional(),
    updatedAt: core.serialization.date().optional(),
});

export declare namespace ResponseFactsUpdateFactsItem {
    export interface Raw {
        id?: Uuid.Raw | null;
        text?: string | null;
        group?: string | null;
        groupId?: Uuid.Raw | null;
        source?: V2SourceEnum.Raw | null;
        isDiscarded?: boolean | null;
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
