/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsGetResponse } from "./DocumentsGetResponse.js";

export const ResponseDocumentList: core.serialization.ObjectSchema<
    serializers.ResponseDocumentList.Raw,
    Corti.ResponseDocumentList
> = core.serialization.object({
    data: core.serialization.list(DocumentsGetResponse).optional(),
});

export declare namespace ResponseDocumentList {
    export interface Raw {
        data?: DocumentsGetResponse.Raw[] | null;
    }
}
