/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Section } from "./Section.js";

export const ResponseAllTemplateSections: core.serialization.ObjectSchema<
    serializers.ResponseAllTemplateSections.Raw,
    Corti.ResponseAllTemplateSections
> = core.serialization.object({
    data: core.serialization.list(Section).optional(),
});

export declare namespace ResponseAllTemplateSections {
    export interface Raw {
        data?: Section.Raw[] | null;
    }
}
