/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { ResponseTranscriptListAllTranscriptsItem } from "./ResponseTranscriptListAllTranscriptsItem.js";

export const ResponseTranscriptListAll: core.serialization.ObjectSchema<
    serializers.ResponseTranscriptListAll.Raw,
    Corti.ResponseTranscriptListAll
> = core.serialization.object({
    transcripts: core.serialization.list(ResponseTranscriptListAllTranscriptsItem).optional(),
});

export declare namespace ResponseTranscriptListAll {
    export interface Raw {
        transcripts?: ResponseTranscriptListAllTranscriptsItem.Raw[] | null;
    }
}
