/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const ResponseAllTemplatesDataItemTranslationsItem: core.serialization.ObjectSchema<
    serializers.ResponseAllTemplatesDataItemTranslationsItem.Raw,
    Corti.ResponseAllTemplatesDataItemTranslationsItem
> = core.serialization.object({
    languagesId: core.serialization.property("languages_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace ResponseAllTemplatesDataItemTranslationsItem {
    export interface Raw {
        languages_id?: string | null;
        name?: string | null;
        description?: string | null;
    }
}
