/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { Encounter } from "./Encounter.js";
import { Patient } from "./Patient.js";

export const ResponseInteraction: core.serialization.ObjectSchema<
    serializers.ResponseInteraction.Raw,
    Corti.ResponseInteraction
> = core.serialization.object({
    id: Uuid,
    assignedUserId: Uuid,
    encounter: Encounter,
    patient: Patient,
    endedAt: core.serialization.date(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
    websocketUrl: core.serialization.string(),
    lastUpdated: core.serialization.date(),
});

export declare namespace ResponseInteraction {
    export interface Raw {
        id: Uuid.Raw;
        assignedUserId: Uuid.Raw;
        encounter: Encounter.Raw;
        patient: Patient.Raw;
        endedAt: string;
        createdAt: string;
        updatedAt: string;
        websocketUrl: string;
        lastUpdated: string;
    }
}
