/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { ResponseFactsCreateFactsItem } from "./ResponseFactsCreateFactsItem.js";

export const ResponseFactsCreate: core.serialization.ObjectSchema<
    serializers.ResponseFactsCreate.Raw,
    Corti.ResponseFactsCreate
> = core.serialization.object({
    facts: core.serialization.list(ResponseFactsCreateFactsItem).optional(),
});

export declare namespace ResponseFactsCreate {
    export interface Raw {
        facts?: ResponseFactsCreateFactsItem.Raw[] | null;
    }
}
