/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { ResponseMetadataCreate } from "./ResponseMetadataCreate.js";
import { Transcript } from "./Transcript.js";
import { UsageInfo } from "./UsageInfo.js";

export const ResponseTranscriptCreate: core.serialization.ObjectSchema<
    serializers.ResponseTranscriptCreate.Raw,
    Corti.ResponseTranscriptCreate
> = core.serialization.object({
    id: Uuid.optional(),
    metadata: ResponseMetadataCreate.optional(),
    transcripts: core.serialization.list(Transcript).optional(),
    usageInfo: UsageInfo.optional(),
    recordingId: Uuid.optional(),
});

export declare namespace ResponseTranscriptCreate {
    export interface Raw {
        id?: Uuid.Raw | null;
        metadata?: ResponseMetadataCreate.Raw | null;
        transcripts?: Transcript.Raw[] | null;
        usageInfo?: UsageInfo.Raw | null;
        recordingId?: Uuid.Raw | null;
    }
}
