/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StatusType: core.serialization.Schema<serializers.StatusType.Raw, Corti.StatusType> =
    core.serialization.enum_([
        "CONFIG_ACCEPTED",
        "CONFIG_DENIED",
        "CONFIG_MISSING",
        "CONFIG_NOT_PROVIDED",
        "CONFIG_ALREADY_RECEIVED",
    ]);

export declare namespace StatusType {
    export type Raw =
        | "CONFIG_ACCEPTED"
        | "CONFIG_DENIED"
        | "CONFIG_MISSING"
        | "CONFIG_NOT_PROVIDED"
        | "CONFIG_ALREADY_RECEIVED";
}
