/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StreamParticipantRole: core.serialization.Schema<
    serializers.StreamParticipantRole.Raw,
    Corti.StreamParticipantRole
> = core.serialization.enum_(["doctor", "patient", "multiple"]);

export declare namespace StreamParticipantRole {
    export type Raw = "doctor" | "patient" | "multiple";
}
