/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StreamConfigModeType: core.serialization.Schema<
    serializers.StreamConfigModeType.Raw,
    Corti.StreamConfigModeType
> = core.serialization.enum_(["facts", "transcription"]);

export declare namespace StreamConfigModeType {
    export type Raw = "facts" | "transcription";
}
