/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { StreamConfigParticipantRole } from "./StreamConfigParticipantRole.js";

export const StreamConfigParticipant: core.serialization.ObjectSchema<
    serializers.StreamConfigParticipant.Raw,
    Corti.StreamConfigParticipant
> = core.serialization.object({
    channel: core.serialization.number(),
    role: StreamConfigParticipantRole,
});

export declare namespace StreamConfigParticipant {
    export interface Raw {
        channel: number;
        role: StreamConfigParticipantRole.Raw;
    }
}
