/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { StreamConfigData } from "./StreamConfigData.js";

export const StreamConfigurationMessage: core.serialization.ObjectSchema<
    serializers.StreamConfigurationMessage.Raw,
    Corti.StreamConfigurationMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("config"),
    configuration: StreamConfigData,
});

export declare namespace StreamConfigurationMessage {
    export interface Raw {
        type: "config";
        configuration: StreamConfigData.Raw;
    }
}
