/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { StreamConfigStatusMessageType } from "./StreamConfigStatusMessageType.js";

export const StreamConfigStatusMessage: core.serialization.ObjectSchema<
    serializers.StreamConfigStatusMessage.Raw,
    Corti.StreamConfigStatusMessage
> = core.serialization.object({
    type: StreamConfigStatusMessageType,
    reason: core.serialization.string().optional(),
});

export declare namespace StreamConfigStatusMessage {
    export interface Raw {
        type: StreamConfigStatusMessageType.Raw;
        reason?: string | null;
    }
}
