/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StreamConfigModeOutputLocale: core.serialization.Schema<
    serializers.StreamConfigModeOutputLocale.Raw,
    Corti.StreamConfigModeOutputLocale
> = core.serialization.enum_(["en", "en-GB", "da", "de", "fr", "de-CH", "sv", "es", "it", "nl", "no", "pt"]);

export declare namespace StreamConfigModeOutputLocale {
    export type Raw = "en" | "en-GB" | "da" | "de" | "fr" | "de-CH" | "sv" | "es" | "it" | "nl" | "no" | "pt";
}
