/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { StreamConfig } from "./StreamConfig.js";

export const StreamConfigMessage: core.serialization.ObjectSchema<
    serializers.StreamConfigMessage.Raw,
    Corti.StreamConfigMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("config"),
    configuration: StreamConfig,
});

export declare namespace StreamConfigMessage {
    export interface Raw {
        type: "config";
        configuration: StreamConfig.Raw;
    }
}
