/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StreamEndedMessage: core.serialization.ObjectSchema<
    serializers.StreamEndedMessage.Raw,
    Corti.StreamEndedMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("ENDED"),
});

export declare namespace StreamEndedMessage {
    export interface Raw {
        type: "ENDED";
    }
}
