// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const StreamFormattingNumbers: core.serialization.Schema<
    serializers.StreamFormattingNumbers.Raw,
    Corti.StreamFormattingNumbers
> = core.serialization.enum_(["numerals_above_nine", "numerals", "as_dictated"]);

export declare namespace StreamFormattingNumbers {
    export type Raw = "numerals_above_nine" | "numerals" | "as_dictated";
}
