// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { StreamAudioEventsConfig } from "./StreamAudioEventsConfig.js";
import { StreamConfigKeyterms } from "./StreamConfigKeyterms.js";
import { StreamConfigMode } from "./StreamConfigMode.js";
import { StreamConfigReplacementsItem } from "./StreamConfigReplacementsItem.js";
import { StreamConfigRetentionPolicy } from "./StreamConfigRetentionPolicy.js";
import { StreamConfigTranscription } from "./StreamConfigTranscription.js";
import { StreamFormatting } from "./StreamFormatting.js";

export const StreamConfig: core.serialization.ObjectSchema<serializers.StreamConfig.Raw, Corti.StreamConfig> =
    core.serialization.object({
        transcription: StreamConfigTranscription,
        mode: StreamConfigMode,
        retentionPolicy: StreamConfigRetentionPolicy.optional(),
        audioEvents: StreamAudioEventsConfig.optional(),
        formatting: StreamFormatting.optional(),
        audioFormat: core.serialization.string().optional(),
        replacements: core.serialization.list(StreamConfigReplacementsItem).optional(),
        keyterms: StreamConfigKeyterms.optional(),
    });

export declare namespace StreamConfig {
    export interface Raw {
        transcription: StreamConfigTranscription.Raw;
        mode: StreamConfigMode.Raw;
        retentionPolicy?: StreamConfigRetentionPolicy.Raw | null;
        audioEvents?: StreamAudioEventsConfig.Raw | null;
        formatting?: StreamFormatting.Raw | null;
        audioFormat?: string | null;
        replacements?: StreamConfigReplacementsItem.Raw[] | null;
        keyterms?: StreamConfigKeyterms.Raw | null;
    }
}
