/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TemplatesWritingStyle } from "./TemplatesWritingStyle.js";
import { TemplatesSectionTranslation } from "./TemplatesSectionTranslation.js";

export const TemplatesSection: core.serialization.ObjectSchema<
    serializers.TemplatesSection.Raw,
    Corti.TemplatesSection
> = core.serialization.object({
    alternateNames: core.serialization.property(
        "alternate_names",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    defaultWritingStyle: core.serialization.property("default_writing_style", TemplatesWritingStyle),
    description: core.serialization.string(),
    key: core.serialization.string(),
    name: core.serialization.string(),
    sectionType: core.serialization.property("section_type", core.serialization.string()),
    translations: core.serialization.list(TemplatesSectionTranslation),
});

export declare namespace TemplatesSection {
    export interface Raw {
        alternate_names?: (string[] | null) | null;
        date_updated?: (string | null) | null;
        default_writing_style: TemplatesWritingStyle.Raw;
        description: string;
        key: string;
        name: string;
        section_type: string;
        translations: TemplatesSectionTranslation.Raw[];
    }
}
