/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TemplatesSection } from "./TemplatesSection.js";

export const TemplatesSectionListResponse: core.serialization.ObjectSchema<
    serializers.TemplatesSectionListResponse.Raw,
    Corti.TemplatesSectionListResponse
> = core.serialization.object({
    data: core.serialization.list(TemplatesSection),
});

export declare namespace TemplatesSectionListResponse {
    export interface Raw {
        data: TemplatesSection.Raw[];
    }
}
