/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeErrorMessageError: core.serialization.ObjectSchema<
    serializers.TranscribeErrorMessageError.Raw,
    Corti.TranscribeErrorMessageError
> = core.serialization.object({
    id: core.serialization.string(),
    title: core.serialization.string(),
    status: core.serialization.number(),
    details: core.serialization.string(),
    doc: core.serialization.string(),
});

export declare namespace TranscribeErrorMessageError {
    export interface Raw {
        id: string;
        title: string;
        status: number;
        details: string;
        doc: string;
    }
}
