// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TranscribeAudioEventsConfig } from "./TranscribeAudioEventsConfig.js";
import { TranscribeCommand } from "./TranscribeCommand.js";
import { TranscribeConfigKeyterms } from "./TranscribeConfigKeyterms.js";
import { TranscribeConfigReplacementsItem } from "./TranscribeConfigReplacementsItem.js";
import { TranscribeConfigTranscriptProcessing } from "./TranscribeConfigTranscriptProcessing.js";
import { TranscribeFormatting } from "./TranscribeFormatting.js";
import { TranscribeSupportedLanguage } from "./TranscribeSupportedLanguage.js";

export const TranscribeConfig: core.serialization.ObjectSchema<
    serializers.TranscribeConfig.Raw,
    Corti.TranscribeConfig
> = core.serialization.object({
    primaryLanguage: TranscribeSupportedLanguage,
    transcriptProcessing: TranscribeConfigTranscriptProcessing.optional(),
    interimResults: core.serialization.boolean().optional(),
    spokenPunctuation: core.serialization.boolean().optional(),
    automaticPunctuation: core.serialization.boolean().optional(),
    commands: core.serialization.list(TranscribeCommand).optional(),
    formatting: TranscribeFormatting.optional(),
    audioEvents: TranscribeAudioEventsConfig.optional(),
    audioFormat: core.serialization.string().optional(),
    replacements: core.serialization.list(TranscribeConfigReplacementsItem).optional(),
    keyterms: TranscribeConfigKeyterms.optional(),
});

export declare namespace TranscribeConfig {
    export interface Raw {
        primaryLanguage: TranscribeSupportedLanguage.Raw;
        transcriptProcessing?: TranscribeConfigTranscriptProcessing.Raw | null;
        interimResults?: boolean | null;
        spokenPunctuation?: boolean | null;
        automaticPunctuation?: boolean | null;
        commands?: TranscribeCommand.Raw[] | null;
        formatting?: TranscribeFormatting.Raw | null;
        audioEvents?: TranscribeAudioEventsConfig.Raw | null;
        audioFormat?: string | null;
        replacements?: TranscribeConfigReplacementsItem.Raw[] | null;
        keyterms?: TranscribeConfigKeyterms.Raw | null;
    }
}
