/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TranscribeConfigStatusMessageType } from "./TranscribeConfigStatusMessageType.js";

export const TranscribeConfigStatusMessage: core.serialization.ObjectSchema<
    serializers.TranscribeConfigStatusMessage.Raw,
    Corti.TranscribeConfigStatusMessage
> = core.serialization.object({
    type: TranscribeConfigStatusMessageType,
    reason: core.serialization.string().optional(),
    sessionId: core.serialization.string(),
});

export declare namespace TranscribeConfigStatusMessage {
    export interface Raw {
        type: TranscribeConfigStatusMessageType.Raw;
        reason?: string | null;
        sessionId: string;
    }
}
