/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TranscriptParticipantRoleEnum } from "./TranscriptParticipantRoleEnum.js";

export const TranscriptsMetadataParticipantsRolesItem: core.serialization.ObjectSchema<
    serializers.TranscriptsMetadataParticipantsRolesItem.Raw,
    Corti.TranscriptsMetadataParticipantsRolesItem
> = core.serialization.object({
    channel: core.serialization.number(),
    role: TranscriptParticipantRoleEnum,
});

export declare namespace TranscriptsMetadataParticipantsRolesItem {
    export interface Raw {
        channel: number;
        role: TranscriptParticipantRoleEnum.Raw;
    }
}
