// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscriptsFormattingOrdinals: core.serialization.Schema<
    serializers.TranscriptsFormattingOrdinals.Raw,
    Corti.TranscriptsFormattingOrdinals
> = core.serialization.enum_(["numerals_above_nine", "as_dictated", "numerals"]);

export declare namespace TranscriptsFormattingOrdinals {
    export type Raw = "numerals_above_nine" | "as_dictated" | "numerals";
}
