/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeSupportedLanguage: core.serialization.Schema<
    serializers.TranscribeSupportedLanguage.Raw,
    Corti.TranscribeSupportedLanguage
> = core.serialization.string();

export declare namespace TranscribeSupportedLanguage {
    export type Raw = string;
}
