/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscriptsParticipantRoleEnum: core.serialization.Schema<
    serializers.TranscriptsParticipantRoleEnum.Raw,
    Corti.TranscriptsParticipantRoleEnum
> = core.serialization.enum_(["doctor", "patient", "multiple"]);

export declare namespace TranscriptsParticipantRoleEnum {
    export type Raw = "doctor" | "patient" | "multiple";
}
