/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TranscriptParticipantRoleEnum } from "./TranscriptParticipantRoleEnum.js";

export const TranscriptsParticipant: core.serialization.ObjectSchema<
    serializers.TranscriptsParticipant.Raw,
    Corti.TranscriptsParticipant
> = core.serialization.object({
    channel: core.serialization.number(),
    role: TranscriptParticipantRoleEnum,
});

export declare namespace TranscriptsParticipant {
    export interface Raw {
        channel: number;
        role: TranscriptParticipantRoleEnum.Raw;
    }
}
