/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TranscriptsListResponseTranscriptsItem } from "./TranscriptsListResponseTranscriptsItem.js";

export const TranscriptsListResponse: core.serialization.ObjectSchema<
    serializers.TranscriptsListResponse.Raw,
    Corti.TranscriptsListResponse
> = core.serialization.object({
    transcripts: core.serialization.list(TranscriptsListResponseTranscriptsItem).optionalNullable(),
});

export declare namespace TranscriptsListResponse {
    export interface Raw {
        transcripts?: (TranscriptsListResponseTranscriptsItem.Raw[] | null) | null;
    }
}
