/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { TranscriptsMetadataParticipantsRolesItem } from "./TranscriptsMetadataParticipantsRolesItem.js";

export const TranscriptsMetadata: core.serialization.ObjectSchema<
    serializers.TranscriptsMetadata.Raw,
    Corti.TranscriptsMetadata
> = core.serialization.object({
    participantsRoles: core.serialization.list(TranscriptsMetadataParticipantsRolesItem).optionalNullable(),
});

export declare namespace TranscriptsMetadata {
    export interface Raw {
        participantsRoles?: (TranscriptsMetadataParticipantsRolesItem.Raw[] | null) | null;
    }
}
