/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeCommandData: core.serialization.ObjectSchema<
    serializers.TranscribeCommandData.Raw,
    Corti.TranscribeCommandData
> = core.serialization.object({
    id: core.serialization.string(),
    variables: core.serialization
        .record(core.serialization.string(), core.serialization.string().optionalNullable())
        .optionalNullable(),
    rawTranscriptText: core.serialization.string(),
    start: core.serialization.number(),
    end: core.serialization.number(),
});

export declare namespace TranscribeCommandData {
    export interface Raw {
        id: string;
        variables?: (Record<string, (string | null) | null | undefined> | null) | null;
        rawTranscriptText: string;
        start: number;
        end: number;
    }
}
