/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscriptParticipant: core.serialization.ObjectSchema<
    serializers.TranscriptParticipant.Raw,
    Corti.TranscriptParticipant
> = core.serialization.object({
    channel: core.serialization.number().optional(),
});

export declare namespace TranscriptParticipant {
    export interface Raw {
        channel?: number | null;
    }
}
