/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeEndedMessage: core.serialization.ObjectSchema<
    serializers.TranscribeEndedMessage.Raw,
    Corti.TranscribeEndedMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("ended"),
});

export declare namespace TranscribeEndedMessage {
    export interface Raw {
        type: "ended";
    }
}
