/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { Uuid } from "./Uuid.js";
import { TranscriptsMetadata } from "./TranscriptsMetadata.js";
import { CommonTranscript } from "./CommonTranscript.js";
import { CommonUsageInfo } from "./CommonUsageInfo.js";

export const TranscriptsResponse: core.serialization.ObjectSchema<
    serializers.TranscriptsResponse.Raw,
    Corti.TranscriptsResponse
> = core.serialization.object({
    id: Uuid,
    metadata: TranscriptsMetadata,
    transcripts: core.serialization.list(CommonTranscript),
    usageInfo: CommonUsageInfo,
    recordingId: Uuid.optional(),
});

export declare namespace TranscriptsResponse {
    export interface Raw {
        id: Uuid.Raw;
        metadata: TranscriptsMetadata.Raw;
        transcripts: CommonTranscript.Raw[];
        usageInfo: CommonUsageInfo.Raw;
        recordingId?: Uuid.Raw | null;
    }
}
