/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscriptsDataTranscriptsItem: core.serialization.ObjectSchema<
    serializers.TranscriptsDataTranscriptsItem.Raw,
    Corti.TranscriptsDataTranscriptsItem
> = core.serialization.object({
    channel: core.serialization.number(),
    participant: core.serialization.number(),
    speakerId: core.serialization.number(),
    text: core.serialization.string(),
    start: core.serialization.number(),
    end: core.serialization.number(),
});

export declare namespace TranscriptsDataTranscriptsItem {
    export interface Raw {
        channel: number;
        participant: number;
        speakerId: number;
        text: string;
        start: number;
        end: number;
    }
}
