/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const V2EncounterStatusEnum: core.serialization.Schema<
    serializers.V2EncounterStatusEnum.Raw,
    Corti.V2EncounterStatusEnum
> = core.serialization.enum_(["planned", "in-progress", "on-hold", "completed", "cancelled", "deleted"]);

export declare namespace V2EncounterStatusEnum {
    export type Raw = "planned" | "in-progress" | "on-hold" | "completed" | "cancelled" | "deleted";
}
