/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const V2GenderEnum: core.serialization.Schema<serializers.V2GenderEnum.Raw, Corti.V2GenderEnum> =
    core.serialization.enum_(["male", "female", "unknown", "other"]);

export declare namespace V2GenderEnum {
    export type Raw = "male" | "female" | "unknown" | "other";
}
