/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ParticipantRoleEnum } from "../../../types/ParticipantRoleEnum.js";

export const RequestTranscriptCreateParticipantsItem: core.serialization.ObjectSchema<
    serializers.RequestTranscriptCreateParticipantsItem.Raw,
    Corti.RequestTranscriptCreateParticipantsItem
> = core.serialization.object({
    channel: core.serialization.number(),
    role: ParticipantRoleEnum,
});

export declare namespace RequestTranscriptCreateParticipantsItem {
    export interface Raw {
        channel: number;
        role: ParticipantRoleEnum.Raw;
    }
}
