/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { V2TranscriptParticipantRoleEnum } from "../../../types/V2TranscriptParticipantRoleEnum.js";

export const RequestTranscriptCreateParticipantsItem: core.serialization.ObjectSchema<
    serializers.RequestTranscriptCreateParticipantsItem.Raw,
    Corti.RequestTranscriptCreateParticipantsItem
> = core.serialization.object({
    channel: core.serialization.number(),
    role: V2TranscriptParticipantRoleEnum,
});

export declare namespace RequestTranscriptCreateParticipantsItem {
    export interface Raw {
        channel: number;
        role: V2TranscriptParticipantRoleEnum.Raw;
    }
}
