/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const TranscriptsListRequestSort: core.serialization.Schema<
    serializers.TranscriptsListRequestSort.Raw,
    Corti.TranscriptsListRequestSort
> = core.serialization.enum_(["createdAt", "updatedAt"]);

export declare namespace TranscriptsListRequestSort {
    export type Raw = "createdAt" | "updatedAt";
}
