/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const TranscriptsCreateRequestModelName: core.serialization.Schema<
    serializers.TranscriptsCreateRequestModelName.Raw,
    Corti.TranscriptsCreateRequestModelName
> = core.serialization.enum_(["base", "enhanced", "premier"]);

export declare namespace TranscriptsCreateRequestModelName {
    export type Raw = "base" | "enhanced" | "premier";
}
