/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetInteractionsIdTranscriptsRequest {
    /**
     * Describes transcript attribute for sorting
     */
    sort?: string | null;
    /**
     * Describes sorting direction
     */
    direction?: Corti.CommonSortingDirectionEnum | null;
    /**
     * The number of transcripts to return. For example, a pageSize of 10 will return a maximum of 10 interactions.
     */
    pageSize?: number | null;
    /**
     * The number of transcripts to skip. For example, index=2 with pageSize=10 will skip the first 10 interactions and return 11-20.
     */
    index?: number | null;
    /**
     * Display full transcripts in listing
     */
    full?: boolean | null;
}
