// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface TranscriptsListRequest {
    /** Display full transcripts in listing */
    full?: boolean;
    /** Sorting order. Allowed values: [asc, desc]. Default is desc. */
    direction?: Corti.CommonSortingDirectionEnum;
}
