// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("AgentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                description: "description",
                systemPrompt: "systemPrompt",
                experts: [
                    {
                        type: "expert",
                        id: "id",
                        name: "name",
                        description: "description",
                        systemPrompt: "systemPrompt",
                    },
                ],
                mcpServers: [{ id: "id", name: "name", transportType: "stdio", authorizationType: "none", url: "url" }],
            },
        ];

        server.mockEndpoint().get("/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.list();
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                description: "description",
                systemPrompt: "systemPrompt",
                experts: [
                    {
                        type: "expert",
                        id: "id",
                        name: "name",
                        description: "description",
                        systemPrompt: "systemPrompt",
                    },
                ],
                mcpServers: [
                    {
                        id: "id",
                        name: "name",
                        transportType: "stdio",
                        authorizationType: "none",
                        url: "url",
                    },
                ],
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agents").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.list();
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.list();
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        { id: "id", name: "name", transportType: "stdio", authorizationType: "none", url: "url" },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.create({
            name: "name",
            description: "description",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        {
                            id: "id",
                            name: "name",
                            transportType: "stdio",
                            authorizationType: "none",
                            url: "url",
                        },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                description: "description",
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                description: "description",
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                description: "description",
            });
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        { id: "id", name: "name", transportType: "stdio", authorizationType: "none", url: "url" },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/agents/12345678-90ab-cdef-gh12-34567890abc")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.get("12345678-90ab-cdef-gh12-34567890abc");
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        {
                            id: "id",
                            name: "name",
                            transportType: "stdio",
                            authorizationType: "none",
                            url: "url",
                        },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agents/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.get("id");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agents/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.get("id");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agents/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.get("id");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/agents/12345678-90ab-cdef-gh12-34567890abc")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.agents.delete("12345678-90ab-cdef-gh12-34567890abc");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agents/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.delete("id");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agents/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.delete("id");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agents/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.delete("id");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        { id: "id", name: "name", transportType: "stdio", authorizationType: "none", url: "url" },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        };

        server
            .mockEndpoint()
            .patch("/agents/12345678-90ab-cdef-gh12-34567890abc")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.update("12345678-90ab-cdef-gh12-34567890abc");
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        {
                            id: "id",
                            name: "name",
                            transportType: "stdio",
                            authorizationType: "none",
                            url: "url",
                        },
                    ],
                },
            ],
            mcpServers: [
                {
                    id: "id",
                    name: "name",
                    transportType: "stdio",
                    authorizationType: "none",
                    authorizationScope: "authorizationScope",
                    url: "url",
                    redirectUrl: "redirectUrl",
                    requiredHeaders: ["requiredHeaders"],
                    optionalHeaders: ["optionalHeaders"],
                },
            ],
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("id");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("id");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("id");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update("id");
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });

    test("getCard (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            protocolVersion: "protocolVersion",
            name: "name",
            description: "description",
            url: "url",
            preferredTransport: "preferredTransport",
            additionalInterfaces: [{ url: "url", transport: "transport" }],
            iconUrl: "iconUrl",
            documentationUrl: "documentationUrl",
            provider: { organization: "organization", url: "url" },
            version: "version",
            capabilities: {
                streaming: true,
                pushNotifications: true,
                stateTransitionHistory: true,
                extensions: [{ uri: "uri" }],
            },
            securitySchemes: { key: "value" },
            security: { key: "value" },
            defaultInputModes: ["defaultInputModes"],
            defaultOutputModes: ["defaultOutputModes"],
            skills: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tags: ["tags"],
                    examples: [
                        {
                            role: "user",
                            parts: [{ kind: "text", text: "text" }],
                            messageId: "messageId",
                            kind: "message",
                        },
                    ],
                    inputModes: ["inputModes"],
                    outputModes: ["outputModes"],
                    security: { key: "value" },
                },
            ],
            supportsAuthenticatedExtendedCard: true,
            signatures: [{ protected: "protected", signature: "signature", header: { key: "value" } }],
        };

        server
            .mockEndpoint()
            .get("/agents/12345678-90ab-cdef-gh12-34567890abc/agent-card.json")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getCard("12345678-90ab-cdef-gh12-34567890abc");
        expect(response).toEqual({
            protocolVersion: "protocolVersion",
            name: "name",
            description: "description",
            url: "url",
            preferredTransport: "preferredTransport",
            additionalInterfaces: [
                {
                    url: "url",
                    transport: "transport",
                },
            ],
            iconUrl: "iconUrl",
            documentationUrl: "documentationUrl",
            provider: {
                organization: "organization",
                url: "url",
            },
            version: "version",
            capabilities: {
                streaming: true,
                pushNotifications: true,
                stateTransitionHistory: true,
                extensions: [
                    {
                        uri: "uri",
                    },
                ],
            },
            securitySchemes: {
                key: "value",
            },
            security: {
                key: "value",
            },
            defaultInputModes: ["defaultInputModes"],
            defaultOutputModes: ["defaultOutputModes"],
            skills: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tags: ["tags"],
                    examples: [
                        {
                            role: "user",
                            parts: [
                                {
                                    kind: "text",
                                    text: "text",
                                },
                            ],
                            messageId: "messageId",
                            kind: "message",
                        },
                    ],
                    inputModes: ["inputModes"],
                    outputModes: ["outputModes"],
                    security: {
                        key: "value",
                    },
                },
            ],
            supportsAuthenticatedExtendedCard: true,
            signatures: [
                {
                    protected: "protected",
                    signature: "signature",
                    header: {
                        key: "value",
                    },
                },
            ],
        });
    });

    test("getCard (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/agent-card.json")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getCard("id");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("getCard (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/agent-card.json")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getCard("id");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("getCard (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/agent-card.json")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getCard("id");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("messageSend (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: { role: "user", parts: [{ kind: "text", text: "text" }], messageId: "messageId", kind: "message" },
        };
        const rawResponseBody = {
            message: {
                role: "user",
                parts: [{ kind: "text", text: "text" }],
                metadata: { key: "value" },
                extensions: ["extensions"],
                referenceTaskIds: ["referenceTaskIds"],
                messageId: "messageId",
                taskId: "taskId",
                contextId: "contextId",
                kind: "message",
            },
            task: {
                id: "id",
                contextId: "contextId",
                status: {
                    state: "submitted",
                    message: {
                        role: "user",
                        parts: [{ kind: "text", text: "text" }],
                        messageId: "messageId",
                        kind: "message",
                    },
                    timestamp: "2024-01-15T09:30:00Z",
                },
                history: [
                    { role: "user", parts: [{ kind: "text", text: "text" }], messageId: "messageId", kind: "message" },
                ],
                artifacts: [{ artifactId: "artifactId", parts: [{ kind: "text", text: "text" }] }],
                metadata: { key: "value" },
                kind: "task",
            },
        };

        server
            .mockEndpoint()
            .post("/agents/12345678-90ab-cdef-gh12-34567890abc/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.messageSend("12345678-90ab-cdef-gh12-34567890abc", {
            message: {
                role: "user",
                parts: [
                    {
                        kind: "text",
                        text: "text",
                    },
                ],
                messageId: "messageId",
                kind: "message",
            },
        });
        expect(response).toEqual({
            message: {
                role: "user",
                parts: [
                    {
                        kind: "text",
                        text: "text",
                    },
                ],
                metadata: {
                    key: "value",
                },
                extensions: ["extensions"],
                referenceTaskIds: ["referenceTaskIds"],
                messageId: "messageId",
                taskId: "taskId",
                contextId: "contextId",
                kind: "message",
            },
            task: {
                id: "id",
                contextId: "contextId",
                status: {
                    state: "submitted",
                    message: {
                        role: "user",
                        parts: [
                            {
                                kind: "text",
                                text: "text",
                            },
                        ],
                        messageId: "messageId",
                        kind: "message",
                    },
                    timestamp: new Date("2024-01-15T09:30:00.000Z"),
                },
                history: [
                    {
                        role: "user",
                        parts: [
                            {
                                kind: "text",
                                text: "text",
                            },
                        ],
                        messageId: "messageId",
                        kind: "message",
                    },
                ],
                artifacts: [
                    {
                        artifactId: "artifactId",
                        parts: [
                            {
                                kind: "text",
                                text: "text",
                            },
                        ],
                    },
                ],
                metadata: {
                    key: "value",
                },
                kind: "task",
            },
        });
    });

    test("messageSend (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                role: "user",
                parts: [
                    { kind: "text", text: "text" },
                    { kind: "text", text: "text" },
                ],
                messageId: "messageId",
                kind: "message",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents/id/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.messageSend("id", {
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    messageId: "messageId",
                    kind: "message",
                },
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("messageSend (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                role: "user",
                parts: [
                    { kind: "text", text: "text" },
                    { kind: "text", text: "text" },
                ],
                messageId: "messageId",
                kind: "message",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents/id/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.messageSend("id", {
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    messageId: "messageId",
                    kind: "message",
                },
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("messageSend (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                role: "user",
                parts: [
                    { kind: "text", text: "text" },
                    { kind: "text", text: "text" },
                ],
                messageId: "messageId",
                kind: "message",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents/id/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.messageSend("id", {
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    messageId: "messageId",
                    kind: "message",
                },
            });
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("messageSend (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                role: "user",
                parts: [
                    { kind: "text", text: "text" },
                    { kind: "text", text: "text" },
                ],
                messageId: "messageId",
                kind: "message",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents/id/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.messageSend("id", {
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    messageId: "messageId",
                    kind: "message",
                },
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("messageSend (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                role: "user",
                parts: [
                    { kind: "text", text: "text" },
                    { kind: "text", text: "text" },
                ],
                messageId: "messageId",
                kind: "message",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agents/id/v1/message:send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.messageSend("id", {
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    messageId: "messageId",
                    kind: "message",
                },
            });
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });

    test("getTask (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            contextId: "contextId",
            status: {
                state: "submitted",
                message: {
                    role: "user",
                    parts: [{ kind: "text", text: "text" }],
                    metadata: { key: "value" },
                    extensions: ["extensions"],
                    referenceTaskIds: ["referenceTaskIds"],
                    messageId: "messageId",
                    taskId: "taskId",
                    contextId: "contextId",
                    kind: "message",
                },
                timestamp: "2024-01-15T09:30:00Z",
            },
            history: [
                {
                    role: "user",
                    parts: [{ kind: "text", text: "text" }],
                    metadata: { key: "value" },
                    extensions: ["extensions"],
                    referenceTaskIds: ["referenceTaskIds"],
                    messageId: "messageId",
                    taskId: "taskId",
                    contextId: "contextId",
                    kind: "message",
                },
            ],
            artifacts: [
                {
                    artifactId: "artifactId",
                    name: "name",
                    description: "description",
                    parts: [{ kind: "text", text: "text" }],
                    metadata: { key: "value" },
                    extensions: ["extensions"],
                },
            ],
            metadata: { key: "value" },
            kind: "task",
        };

        server
            .mockEndpoint()
            .get("/agents/12345678-90ab-cdef-gh12-34567890abc/v1/tasks/taskId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getTask("12345678-90ab-cdef-gh12-34567890abc", "taskId");
        expect(response).toEqual({
            id: "id",
            contextId: "contextId",
            status: {
                state: "submitted",
                message: {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    metadata: {
                        key: "value",
                    },
                    extensions: ["extensions"],
                    referenceTaskIds: ["referenceTaskIds"],
                    messageId: "messageId",
                    taskId: "taskId",
                    contextId: "contextId",
                    kind: "message",
                },
                timestamp: new Date("2024-01-15T09:30:00.000Z"),
            },
            history: [
                {
                    role: "user",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    metadata: {
                        key: "value",
                    },
                    extensions: ["extensions"],
                    referenceTaskIds: ["referenceTaskIds"],
                    messageId: "messageId",
                    taskId: "taskId",
                    contextId: "contextId",
                    kind: "message",
                },
            ],
            artifacts: [
                {
                    artifactId: "artifactId",
                    name: "name",
                    description: "description",
                    parts: [
                        {
                            kind: "text",
                            text: "text",
                        },
                    ],
                    metadata: {
                        key: "value",
                    },
                    extensions: ["extensions"],
                },
            ],
            metadata: {
                key: "value",
            },
            kind: "task",
        });
    });

    test("getTask (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/tasks/taskId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getTask("id", "taskId");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("getTask (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/tasks/taskId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getTask("id", "taskId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("getTask (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/tasks/taskId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getTask("id", "taskId");
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("getTask (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/tasks/taskId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getTask("id", "taskId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("getContext (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            items: [
                {
                    id: "id",
                    contextId: "contextId",
                    status: { state: "submitted" },
                    history: [
                        {
                            role: "user",
                            parts: [{ kind: "text", text: "text" }],
                            messageId: "messageId",
                            kind: "message",
                        },
                    ],
                    artifacts: [{ artifactId: "artifactId", parts: [{ kind: "text", text: "text" }] }],
                    metadata: { key: "value" },
                    kind: "task",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/agents/12345678-90ab-cdef-gh12-34567890abc/v1/contexts/contextId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getContext("12345678-90ab-cdef-gh12-34567890abc", "contextId");
        expect(response).toEqual({
            id: "id",
            items: [
                {
                    id: "id",
                    contextId: "contextId",
                    status: {
                        state: "submitted",
                    },
                    history: [
                        {
                            role: "user",
                            parts: [
                                {
                                    kind: "text",
                                    text: "text",
                                },
                            ],
                            messageId: "messageId",
                            kind: "message",
                        },
                    ],
                    artifacts: [
                        {
                            artifactId: "artifactId",
                            parts: [
                                {
                                    kind: "text",
                                    text: "text",
                                },
                            ],
                        },
                    ],
                    metadata: {
                        key: "value",
                    },
                    kind: "task",
                },
            ],
        });
    });

    test("getContext (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getContext("id", "contextId");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("getContext (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getContext("id", "contextId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("getContext (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getContext("id", "contextId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("deleteContext (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/agents/12345678-90ab-cdef-gh12-34567890abc/v1/contexts/contextId")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.agents.deleteContext("12345678-90ab-cdef-gh12-34567890abc", "contextId");
        expect(response).toEqual(undefined);
    });

    test("deleteContext (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteContext("id", "contextId");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("deleteContext (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteContext("id", "contextId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("deleteContext (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/agents/id/v1/contexts/contextId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteContext("id", "contextId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("getRegistryExperts (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            experts: [
                {
                    name: "name",
                    displayName: "displayName",
                    displayDescription: "displayDescription",
                    description: "description",
                    mcpServers: [{ name: "name", authorizationType: "none" }],
                    configSchema: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/agents/registry/experts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getRegistryExperts({
            limit: 100,
            offset: 0,
        });
        expect(response).toEqual({
            experts: [
                {
                    name: "name",
                    displayName: "displayName",
                    displayDescription: "displayDescription",
                    description: "description",
                    mcpServers: [
                        {
                            name: "name",
                            authorizationType: "none",
                        },
                    ],
                    configSchema: {
                        key: "value",
                    },
                },
            ],
        });
    });

    test("getRegistryExperts (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/registry/experts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getRegistryExperts();
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("getRegistryExperts (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/registry/experts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getRegistryExperts();
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("getRegistryExperts (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/agents/registry/experts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getRegistryExperts();
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });
});
