// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { AgentsLifecycle } from "../../../../../../types/AgentsLifecycle.js";
import { AgentsVisibility } from "../../../../../../types/AgentsVisibility.js";
import { CommonConnectorCreateRequest } from "../../../../../../types/CommonConnectorCreateRequest.js";

export const AgenticAgentsPatchRequest: core.serialization.Schema<
    serializers.agentic.AgenticAgentsPatchRequest.Raw,
    Corti.agentic.AgenticAgentsPatchRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optionalNullable(),
    systemPrompt: core.serialization.string().optionalNullable(),
    model: core.serialization.string().optionalNullable(),
    maxLoops: core.serialization.number().optional(),
    visibility: AgentsVisibility.optional(),
    lifecycle: AgentsLifecycle.optional(),
    connectors: core.serialization.list(CommonConnectorCreateRequest).optionalNullable(),
    labels: core.serialization
        .record(core.serialization.string(), core.serialization.string().nullable())
        .optionalNullable(),
});

export declare namespace AgenticAgentsPatchRequest {
    export interface Raw {
        name?: string | null;
        description?: (string | null | undefined) | null;
        systemPrompt?: (string | null | undefined) | null;
        model?: (string | null | undefined) | null;
        maxLoops?: number | null;
        visibility?: AgentsVisibility.Raw | null;
        lifecycle?: AgentsLifecycle.Raw | null;
        connectors?: (CommonConnectorCreateRequest.Raw[] | null | undefined) | null;
        labels?: (Record<string, string | null | undefined> | null | undefined) | null;
    }
}
