// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { AgentsLabels } from "../../../../../../types/AgentsLabels.js";
import { AgentsLifecycle } from "../../../../../../types/AgentsLifecycle.js";
import { AgentsVisibility } from "../../../../../../types/AgentsVisibility.js";
import { CommonConnectorCreateRequest } from "../../../../../../types/CommonConnectorCreateRequest.js";

export const AgenticAgentsCreateRequest: core.serialization.Schema<
    serializers.agentic.AgenticAgentsCreateRequest.Raw,
    Corti.agentic.AgenticAgentsCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    systemPrompt: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    maxLoops: core.serialization.number().optional(),
    visibility: AgentsVisibility.optional(),
    lifecycle: AgentsLifecycle.optional(),
    connectors: core.serialization.list(CommonConnectorCreateRequest).optional(),
    labels: AgentsLabels.optional(),
});

export declare namespace AgenticAgentsCreateRequest {
    export interface Raw {
        name: string;
        description?: string | null;
        systemPrompt?: string | null;
        model?: string | null;
        maxLoops?: number | null;
        visibility?: AgentsVisibility.Raw | null;
        lifecycle?: AgentsLifecycle.Raw | null;
        connectors?: CommonConnectorCreateRequest.Raw[] | null;
        labels?: AgentsLabels.Raw | null;
    }
}
