/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { Auth } from "./api/resources/auth/client/Client.js";
import { mergeHeaders } from "./core/headers.js";
import { Interactions } from "./api/resources/interactions/client/Client.js";
import { Recordings } from "./api/resources/recordings/client/Client.js";
import { Transcripts } from "./api/resources/transcripts/client/Client.js";
import { Stream } from "./api/resources/stream/client/Client.js";

export declare namespace CortiClient {
    export interface Options {
        environment: core.Supplier<environments.CortiEnvironment | environments.CortiEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        clientId: core.Supplier<string>;
        clientSecret: core.Supplier<string>;
        /** Override the Tenant-Name header */
        tenantName: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the Tenant-Name header */
        tenantName?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class CortiClient {
    protected readonly _options: CortiClient.Options;
    private readonly _oauthTokenProvider: core.OAuthTokenProvider;
    protected _interactions: Interactions | undefined;
    protected _recordings: Recordings | undefined;
    protected _transcripts: Transcripts | undefined;
    protected _auth: Auth | undefined;
    protected _stream: Stream | undefined;

    constructor(_options: CortiClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "Tenant-Name": _options?.tenantName,
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@corti/core",
                    "X-Fern-SDK-Version": "0.0.0-alpha.4",
                    "User-Agent": "@corti/core/0.0.0-alpha.4",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };

        this._oauthTokenProvider = new core.OAuthTokenProvider({
            clientId: this._options.clientId,
            clientSecret: this._options.clientSecret,
            authClient: new Auth({
                environment: this._options.environment,
            }),
        });
    }

    public get interactions(): Interactions {
        return (this._interactions ??= new Interactions({
            ...this._options,
            token: async () => await this._oauthTokenProvider.getToken(),
        }));
    }

    public get recordings(): Recordings {
        return (this._recordings ??= new Recordings({
            ...this._options,
            token: async () => await this._oauthTokenProvider.getToken(),
        }));
    }

    public get transcripts(): Transcripts {
        return (this._transcripts ??= new Transcripts({
            ...this._options,
            token: async () => await this._oauthTokenProvider.getToken(),
        }));
    }

    public get auth(): Auth {
        return (this._auth ??= new Auth({
            ...this._options,
            token: async () => await this._oauthTokenProvider.getToken(),
        }));
    }

    public get stream(): Stream {
        return (this._stream ??= new Stream({
            ...this._options,
            token: async () => await this._oauthTokenProvider.getToken(),
        }));
    }
}
