/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CortiEnvironmentUrls {
    base: string;
    wss: string;
    login: string;
}

export const CortiEnvironment = {
    BetaEu: {
        base: "https://api.beta-eu.corti.app/v2",
        wss: "wss://api.beta-eu.corti.app/v2",
        login: "https://auth.beta-eu.corti.app/realms",
    },
    Eu: {
        base: "https://api.eu.corti.app/v2",
        wss: "wss://api.eu.corti.app/v2",
        login: "https://auth.eu.corti.app/realms",
    },
    Us: {
        base: "https://api.us.corti.app/v2",
        wss: "wss://api.us.corti.app/v2",
        login: "https://auth.us.corti.app/realms",
    },
} as const;

export type CortiEnvironment = typeof CortiEnvironment.BetaEu | typeof CortiEnvironment.Eu | typeof CortiEnvironment.Us;
