/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Uuid } from "../../../types/Uuid.js";

export const FactsBatchUpdateRequestFactsItem: core.serialization.ObjectSchema<
    serializers.FactsBatchUpdateRequestFactsItem.Raw,
    Corti.FactsBatchUpdateRequestFactsItem
> = core.serialization.object({
    factId: Uuid,
    isDiscarded: core.serialization.boolean().optional(),
    text: core.serialization.string().optional(),
    group: core.serialization.string().optional(),
});

export declare namespace FactsBatchUpdateRequestFactsItem {
    export interface Raw {
        factId: Uuid.Raw;
        isDiscarded?: boolean | null;
        text?: string | null;
        group?: string | null;
    }
}
