/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         context: [{
 *                 type: "facts",
 *                 data: [{
 *                         text: "text",
 *                         source: "core"
 *                     }]
 *             }],
 *         templateKey: "templateKey",
 *         outputLanguage: "outputLanguage"
 *     }
 */
export interface RequestDocumentCreate {
    /** An array of context objects. */
    context: Corti.RequestDocumentCreateContextItem[];
    /** The key of the template that informs on what kind of document is to be generated. */
    templateKey: string;
    /** Template details if the template should be generated during the request. */
    template?: Corti.DocumentTemplate;
    /** An optional name for the document. */
    name?: string;
    modelName?: string;
    /** The language in which the document will be generated. Check https://docs.corti.ai/about/languages for more. */
    outputLanguage: string;
}
